// Copyright (C) 2025 SyncMyOrders Sp. z o.o.
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Canonical WIT contracts of every runtara component.
//!
//! Packages are grouped by who may import them, so each package is one
//! privilege class and one versioning cadence:
//!
//! - `runtara:agent`: the shared vocabulary and the agent export shape;
//! - `runtara:host`: services any ordinary agent and every workflow may import;
//! - `runtara:workflow`: the host ABI of compiled workflow logic only;
//! - `runtara:workflow-stdlib`: the compiler-private JSON stdlib component;
//! - `runtara:trusted`: approved trusted agents only;
//! - `runtara:control`: the control agent only.
//!
//! Each agent additionally exports its own `runtara:agent-<id>` package,
//! generated by [`agent_package`]; the unique package name is what lets
//! composition tell agents apart.
//!
//! # Versioning
//!
//! A parked run wakes on the artifact it was built from, possibly after the
//! host was upgraded, and wasmtime lifts records, variants and enums exactly.
//! So released WIT is never edited, only versioned:
//!
//! - An **additive** change (a new function or interface in a package) bumps
//!   the package minor version. The host links only the newest minor: the
//!   wasmtime linker resolves an import of `@1.0.0` against a semver-compatible
//!   `@1.x` definition.
//! - **Any change to an existing function or type** bumps the major version,
//!   and the host links the old major beside the new one until no parked run
//!   needs it.

/// Expands to the version shared by every runtara WIT package. Textually
/// scoped, so it reaches every module below.
macro_rules! v {
    () => {
        "1.0.0"
    };
}

/// Version shared by every runtara WIT package.
pub const VERSION: &str = v!();

/// Directory holding one sub-directory of WIT per package. Guest crates and
/// proc macros point `wit_bindgen` here instead of at relative paths.
pub const WIT_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/wit");

/// `runtara:agent`: the shared vocabulary and the agent export shape.
pub mod agent {
    pub const PACKAGE: &str = concat!("runtara:agent@", v!());
    /// `error-info`, used by every component.
    pub const TYPES: &str = concat!("runtara:agent/types@", v!());
    /// Any version of the types interface.
    pub const TYPES_PREFIX: &str = "runtara:agent/types@";
    /// Continuation delivery, imported by suspending agents.
    pub const CONTINUATION: &str = concat!("runtara:agent/continuation@", v!());
    /// The reference capabilities shape the host binds against.
    pub const CAPABILITIES: &str = concat!("runtara:agent/capabilities@", v!());
    pub const WIT: &str = include_str!("../wit/agent/runtara-agent.wit");
}

/// `runtara:host`: services any ordinary agent and every workflow may import.
pub mod host {
    pub const PACKAGE: &str = concat!("runtara:host@", v!());
    /// Interface-name prefix of every host service.
    pub const PREFIX: &str = "runtara:host/";
    pub const HTTP: &str = concat!("runtara:host/http@", v!());
    pub const SQL: &str = concat!("runtara:host/sql@", v!());
    pub const CONNECTIONS: &str = concat!("runtara:host/connections@", v!());
    pub const TIMERS: &str = concat!("runtara:host/timers@", v!());
    pub const WIT: &str = include_str!("../wit/host/runtara-host.wit");
}

/// `runtara:workflow`: the host ABI of compiled workflow logic only.
pub mod workflow {
    pub const PACKAGE: &str = concat!("runtara:workflow@", v!());
    /// Interface-name prefix of every workflow interface.
    pub const PREFIX: &str = "runtara:workflow/";
    /// Agent id of a top-level workflow's entry package: a root run exports
    /// `runtara:agent-workflow-agent/capabilities` (a published workflow-agent
    /// exports its slug instead). Reserved, so no workflow slug can take it.
    pub const ENTRY_AGENT_ID: &str = "workflow-agent";
    /// The entry export of a top-level workflow.
    pub const ENTRY: &str = concat!("runtara:agent-workflow-agent/capabilities@", v!());
    /// The capability id every workflow entry answers.
    pub const ENTRY_CAPABILITY: &str = "run";
    /// Custom section the compiler writes into every workflow-logic component.
    /// It is how the host tells compiled workflow logic, which may bind this
    /// package, from an agent: both export a `capabilities` interface.
    pub const LOGIC_SECTION: &str = "runtara.direct_workflow.abi";
    pub const RUNTIME: &str = concat!("runtara:workflow/runtime@", v!());
    pub const TASKS: &str = concat!("runtara:workflow/tasks@", v!());
    pub const OPERATION: &str = concat!("runtara:workflow/operation@", v!());
    /// Any version of the operation interface.
    pub const OPERATION_PREFIX: &str = "runtara:workflow/operation@";
    pub const WAITS: &str = concat!("runtara:workflow/waits@", v!());
    /// Any version of the waits interface.
    pub const WAITS_PREFIX: &str = "runtara:workflow/waits@";
    pub const WIT: &str = include_str!("../wit/workflow/runtara-workflow.wit");
}

/// `runtara:workflow-stdlib`: the compiler-private JSON stdlib component.
pub mod stdlib {
    pub const PACKAGE: &str = concat!("runtara:workflow-stdlib@", v!());
    pub const JSON: &str = concat!("runtara:workflow-stdlib/json@", v!());
    pub const WIT: &str = include_str!("../wit/workflow-stdlib/runtara-workflow-stdlib.wit");
}

/// `runtara:trusted`: approved trusted agents only.
pub mod trusted {
    pub const PACKAGE: &str = concat!("runtara:trusted@", v!());
    /// Imported by a trusted agent's ordinary copy.
    pub const EXECUTOR: &str = concat!("runtara:trusted/executor@", v!());
    /// Exported by a trusted agent, called only by the host executor.
    pub const EXECUTION: &str = concat!("runtara:trusted/execution@", v!());
    pub const WIT: &str = include_str!("../wit/trusted/runtara-trusted.wit");
}

/// `runtara:control`: the control agent only.
pub mod control {
    pub const PACKAGE: &str = concat!("runtara:control@", v!());
    /// Interface-name prefix of every control interface.
    pub const PREFIX: &str = "runtara:control/";
    pub const TYPES: &str = concat!("runtara:control/types@", v!());
    /// Host control operations: real only in control executor stores.
    pub const API: &str = concat!("runtara:control/api@", v!());
    /// What the composed control copy forwards to.
    pub const EXECUTOR: &str = concat!("runtara:control/executor@", v!());
    /// Exported by the control agent, called only by the host executor.
    pub const EXECUTION: &str = concat!("runtara:control/execution@", v!());
    pub const WIT: &str = include_str!("../wit/control/runtara-control.wit");
}

/// The resolved WASI inputs the workflow compiler imports (managed by
/// `wit-deps` under `wit/deps`).
pub mod wasi {
    pub const IO_POLL_WIT: &str = include_str!("../wit/deps/io/poll.wit");
    pub const MONOTONIC_CLOCK_WIT: &str = include_str!("../wit/deps/clocks/monotonic-clock.wit");
    pub const MONOTONIC_CLOCK: &str = "wasi:clocks/monotonic-clock@0.2.3";
}

/// Every package as `(file name, WIT text)`, in dependency order: a package
/// comes after every package it `use`s. This is the only place that knows the
/// order.
pub const PACKAGES: &[(&str, &str)] = &[
    ("runtara-agent.wit", agent::WIT),
    ("runtara-host.wit", host::WIT),
    ("runtara-workflow.wit", workflow::WIT),
    ("runtara-workflow-stdlib.wit", stdlib::WIT),
    ("runtara-trusted.wit", trusted::WIT),
    ("runtara-control.wit", control::WIT),
];

/// A `wit_parser` resolve holding every runtara package once, after the WASI
/// clock and poll interfaces the workflow compiler imports. Callers add
/// their own packages (per-agent packages, a workflow world) on top; a world
/// imports only what it names, so the unused packages are harmless.
#[cfg(any(test, feature = "resolve"))]
pub fn resolve() -> Result<wit_parser::Resolve, String> {
    let mut resolve = wit_parser::Resolve::default();
    let wasi = [
        ("wasi-io-poll.wit", wasi::IO_POLL_WIT),
        ("wasi-monotonic-clock.wit", wasi::MONOTONIC_CLOCK_WIT),
    ];
    for (name, wit) in wasi.iter().chain(PACKAGES) {
        resolve
            .push_str(name, wit)
            .map_err(|error| format!("{name}: {error:#}"))?;
    }
    Ok(resolve)
}

/// Which interfaces a generated `runtara:agent-<id>` package declares.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct AgentShape {
    /// The compiler's isolated-agent variant: `scoped-capabilities-v3`, whose
    /// `invoke` also takes the logical call context.
    pub scoped: bool,
    /// A suspending agent: import the continuation of the operation it runs in.
    pub suspendable: bool,
    /// Also export `runtara:trusted/execution`.
    pub trusted: bool,
    /// Import the control executor and API, and export
    /// `runtara:control/execution`.
    pub control: bool,
}

/// Name of the per-agent capabilities interface for `shape`.
pub fn capabilities_interface(shape: AgentShape) -> &'static str {
    if shape.scoped {
        "scoped-capabilities-v3"
    } else {
        "capabilities"
    }
}

/// The `runtara:agent-<id>` package an agent exports, and the compiler
/// imports, for `id` (the agent id in kebab case).
pub fn agent_package(id: &str, shape: AgentShape) -> String {
    let version = VERSION;
    let interface = capabilities_interface(shape);
    // The scoped isolation adapter's private interface keeps the bare list:
    // the host adapter, not the agent, owns suspension there.
    let result = if shape.scoped { "list<u8>" } else { "outcome" };
    let context = if shape.scoped {
        "\n        path: string, call-site: u32, activation: u32, attempt: u64,"
    } else {
        ""
    };
    let mut wit = format!(
        "package runtara:agent-{id}@{version};\n\
         \n\
         interface {interface} {{\n    \
             use runtara:agent/types@{version}.{{error-info, outcome}};\n    \
             invoke: async func(\n        \
                 capability-id: string,\n        \
                 input: list<u8>,{context}\n    \
             ) -> result<{result}, error-info>;\n\
         }}\n"
    );
    wit.push_str("\nworld agent {\n");
    if shape.suspendable {
        wit.push_str(&format!("    import {};\n", agent::CONTINUATION));
    }
    if shape.control {
        wit.push_str(&format!("    import {};\n", control::EXECUTOR));
        wit.push_str(&format!("    import {};\n", control::API));
    }
    wit.push_str(&format!("    export {interface};\n"));
    if shape.trusted {
        wit.push_str(&format!("    export {};\n", trusted::EXECUTION));
    }
    if shape.control {
        wit.push_str(&format!("    export {};\n", control::EXECUTION));
    }
    wit.push_str("}\n");
    wit
}

#[cfg(test)]
mod tests;
