;; Synthetic Agent ABI fixture: cleanup completes normally after cancellation.
;; Used with publicly compiled DSL parents. A five-minute timer cannot complete
;; within the test; the second invocation traps unless cleanup ran exactly once.
;; Built HTTP Agents have separate real-network interruption coverage.
(component
  (import "runtara:workflow-runtime/runtime@0.4.0" (instance $runtime
    (export "custom-event" (func (param "kind" string) (param "payload" (list u8))
      (result (result (error string)))))))
  (import "runtara:host-io/timers@0.1.0" (instance $timers
    (export "sleep" (func async (param "ms" u64)))))
  (type $error (record (field "code" string) (field "message" string)
    (field "category" string) (field "severity" string) (field "retryable" bool)
    (field "retry-after-ms" (option u64)) (field "attributes" (option string))))
  (core module $memory
    (memory (export "memory") 1)
    (global $heap (mut i32) (i32.const 4096))
    (func (export "realloc") (param i32 i32 i32) (param $size i32) (result i32) (local $p i32)
      (local.set $p (global.get $heap))
      (global.set $heap (i32.add (global.get $heap) (local.get $size)))
      (local.get $p)))
  (core instance $memory (instantiate $memory))
  (core func $request (canon lower (func $timers "sleep") async))
  (core func $event (canon lower (func $runtime "custom-event")
    (memory $memory "memory") (realloc (func $memory "realloc"))))
  (core func $new (canon waitable-set.new))
  (core func $join (canon waitable.join))
  (core func $drop-set (canon waitable-set.drop))
  (core func $cancel (canon subtask.cancel))
  (core func $drop (canon subtask.drop))
  (core func $return (canon task.return (result (result (list u8) (error $error))) (memory $memory "memory")))
  (core module $code
    (import "m" "memory" (memory 1))
    (import "h" "request" (func $request (param i64) (result i32)))
    (import "h" "event" (func $event (param i32 i32 i32 i32 i32)))
    (import "h" "new" (func $new (result i32)))
    (import "h" "join" (func $join (param i32 i32)))
    (import "h" "drop-set" (func $drop-set (param i32)))
    (import "h" "cancel" (func $cancel (param i32) (result i32)))
    (import "h" "drop" (func $drop (param i32)))
    (import "h" "return" (func $return (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i64 i32 i32 i32)))
    (global $calls (mut i32) (i32.const 0))
    (global $cleaned (mut i32) (i32.const 0))
    (global $handle (mut i32) (i32.const 0))
    (global $set (mut i32) (i32.const 0))
    (data (i32.const 1024) "{\22status_code\22:200,\22body\22:\22ok\22}")
    (data (i32.const 2048) "late-return-start")
    (data (i32.const 2080) "late-return-cleanup")
    (func $observe (param $ptr i32) (param $len i32)
      (call $event (local.get $ptr) (local.get $len) (i32.const 0) (i32.const 0) (i32.const 128))
      (if (i32.load (i32.const 128)) (then unreachable)))
    (func $finish
      ;; The canonical result flattens to 15 values: ok tag + list pointer/length,
      ;; followed by zero padding for the inactive error-info alternative.
      (call $return (i32.const 0) (i32.const 1024) (i32.const 31)
        (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)
        (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)
        (i64.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
    (func (export "invoke") (param i32 i32 i32 i32) (result i32) (local $status i32)
      (global.set $calls (i32.add (global.get $calls) (i32.const 1)))
      (if (i32.eq (global.get $calls) (i32.const 2)) (then
        ;; Recovery reuses this component only after the cancellation callback.
        (if (i32.ne (global.get $cleaned) (i32.const 1)) (then unreachable))
        (call $finish) (return (i32.const 0))))
      (if (i32.ne (global.get $calls) (i32.const 1)) (then unreachable))
      (call $observe (i32.const 2048) (i32.const 17))
      (local.set $status (call $request (i64.const 300000)))
      (if (i32.eq (i32.and (local.get $status) (i32.const 15)) (i32.const 2))
        (then (call $finish) (return (i32.const 0))))
      (global.set $handle (i32.shr_u (local.get $status) (i32.const 4)))
      (global.set $set (call $new))
      (call $join (global.get $handle) (global.get $set))
      (i32.or (i32.shl (global.get $set) (i32.const 4)) (i32.const 2)))
    (func (export "callback") (param $event i32) (param $handle i32) (param $status i32) (result i32)
      (if (i32.eq (local.get $event) (i32.const 6))
        (then
          (call $join (global.get $handle) (i32.const 0))
          (if (i32.ne (call $cancel (global.get $handle)) (i32.const 4)) (then unreachable))
          (call $drop (global.get $handle))
          (call $drop-set (global.get $set))
          (global.set $cleaned (i32.const 1))
          (call $observe (i32.const 2080) (i32.const 19))
          ;; Normal task.return is permitted during cancellation cleanup.
          (call $finish)
          (return (i32.const 0))))
      (if (i32.ne (local.get $event) (i32.const 1)) (then unreachable))
      (if (i32.ne (local.get $status) (i32.const 2)) (then unreachable))
      (call $drop (local.get $handle))
      (call $drop-set (global.get $set))
      (call $finish)
      (i32.const 0)))
  (core instance $code (instantiate $code
    (with "m" (instance $memory))
    (with "h" (instance
      (export "event" (func $event)) (export "request" (func $request)) (export "new" (func $new))
      (export "join" (func $join)) (export "drop-set" (func $drop-set))
      (export "cancel" (func $cancel)) (export "drop" (func $drop))
      (export "return" (func $return))))))
  (func $invoke async (param "capability-id" string) (param "input" (list u8))
    (result (result (list u8) (error $error)))
    (canon lift (core func $code "invoke") async (callback (func $code "callback"))
      (memory $memory "memory") (realloc (func $memory "realloc"))))
  (instance $capabilities
    (export "error-info" (type $error))
    (export "invoke" (func $invoke)))
  (export "runtara:agent-http/capabilities@0.4.0" (instance $capabilities)))
