;; Qualification fixture, not a second execution backend. Both guest components
;; share one Store. Only I/O, a readiness barrier, and trace observation are native.
(component
  (import "request" (func $request async))
  (import "cleanup" (func $cleanup async))
  (import "ready" (func $ready async))
  (import "trace" (func $trace (param "event" u32)))
  (import "runtara:host-io/timers@0.1.0" (instance $timers
    (export "sleep" (func async (param "ms" u64)))))
  (component $agent
    (import "request" (func $request async))
    (import "cleanup" (func $cleanup async))
    (import "trace" (func $trace (param "event" u32)))
    (core func $request (canon lower (func $request) async))
    (core func $cleanup (canon lower (func $cleanup) async))
    (core func $trace (canon lower (func $trace)))
    (core func $new (canon waitable-set.new))
    (core func $join (canon waitable.join))
    (core func $drop-set (canon waitable-set.drop))
    (core func $cancel (canon subtask.cancel))
    (core func $drop (canon subtask.drop))
    (core func $cancelled (canon task.cancel))
    (core func $return (canon task.return))
    (core module $code
      (import "h" "request" (func $request (result i32)))
      (import "h" "cleanup" (func $cleanup (result i32)))
      (import "h" "trace" (func $trace (param i32)))
      (import "h" "new" (func $new (result i32)))
      (import "h" "join" (func $join (param i32 i32)))
      (import "h" "drop-set" (func $drop-set (param i32)))
      (import "h" "cancel" (func $cancel (param i32) (result i32)))
      (import "h" "drop" (func $drop (param i32)))
      (import "h" "cancelled" (func $cancelled))
      (import "h" "return" (func $return))
      (global $set (mut i32) (i32.const 0))
      (global $handle (mut i32) (i32.const 0))
      (global $cancelling (mut i32) (i32.const 0))
      (func $pending (param $status i32)
        (if (i32.ne (i32.and (local.get $status) (i32.const 15)) (i32.const 1))
          (then unreachable))
        (global.set $handle (i32.shr_u (local.get $status) (i32.const 4)))
        (call $join (global.get $handle) (global.get $set)))
      (func $wait (result i32)
        (i32.or (i32.shl (global.get $set) (i32.const 4)) (i32.const 2)))
      (func (export "run") (result i32)
        (global.set $set (call $new))
        (global.set $cancelling (i32.const 0))
        (call $pending (call $request))
        (call $wait))
      (func (export "callback") (param $event i32) (param $handle i32) (param $status i32) (result i32)
        (if (i32.eq (local.get $event) (i32.const 6))
          (then
            (if (global.get $cancelling) (then unreachable))
            (global.set $cancelling (i32.const 1))
            (call $trace (i32.const 20))
            (call $join (global.get $handle) (i32.const 0))
            (if (i32.ne (call $cancel (global.get $handle)) (i32.const 4))
              (then unreachable))
            (call $drop (global.get $handle))
            (call $trace (i32.const 30))
            {{CLEANUP}}
            (call $pending (call $cleanup))
            (return (call $wait))))
        (if (i32.ne (local.get $event) (i32.const 1)) (then unreachable))
        (if (i32.ne (local.get $handle) (global.get $handle)) (then unreachable))
        (if (i32.lt_u (local.get $status) (i32.const 2)) (then (return (call $wait))))
        (if (i32.ne (local.get $status) (i32.const 2)) (then unreachable))
        (call $drop (global.get $handle))
        (call $drop-set (global.get $set))
        (call $trace (i32.const 50))
        {{RESOLVE}}
        (i32.const 0)))
    (core instance $code (instantiate $code (with "h" (instance
      (export "request" (func $request)) (export "cleanup" (func $cleanup))
      (export "trace" (func $trace)) (export "new" (func $new))
      (export "join" (func $join)) (export "drop-set" (func $drop-set))
      (export "cancel" (func $cancel)) (export "drop" (func $drop))
      (export "cancelled" (func $cancelled)) (export "return" (func $return))))))
    (func (export "run") async
      (canon lift (core func $code "run") async (callback (func $code "callback")))))
  (instance $agent (instantiate $agent
    (with "request" (func $request)) (with "cleanup" (func $cleanup))
    (with "trace" (func $trace))))
  (component $workflow
    (import "target" (func $target async))
    (import "ready" (func $ready async))
    (import "sleep" (func $sleep async (param "ms" u64)))
    (import "trace" (func $trace (param "event" u32)))
    (core module $memory (memory (export "memory") 1))
    (core instance $memory (instantiate $memory))
    (core func $target (canon lower (func $target) async))
    (core func $ready (canon lower (func $ready)))
    (core func $sleep (canon lower (func $sleep) async))
    (core func $trace (canon lower (func $trace)))
    (core func $cancel (canon subtask.cancel async))
    (core func $drop (canon subtask.drop))
    (core func $new (canon waitable-set.new))
    (core func $join (canon waitable.join))
    (core func $wait (canon waitable-set.wait (memory $memory "memory")))
    (core func $drop-set (canon waitable-set.drop))
    (core module $code
      (import "m" "memory" (memory 1))
      (import "h" "target" (func $target (result i32)))
      (import "h" "ready" (func $ready))
      (import "h" "sleep" (func $sleep (param i64) (result i32)))
      (import "h" "trace" (func $trace (param i32)))
      (import "h" "cancel" (func $cancel (param i32) (result i32)))
      (import "h" "drop" (func $drop (param i32)))
      (import "h" "new" (func $new (result i32)))
      (import "h" "join" (func $join (param i32 i32)))
      (import "h" "wait" (func $wait (param i32 i32) (result i32)))
      (import "h" "drop-set" (func $drop-set (param i32)))
      (func $handle (param $status i32) (result i32)
        (if (i32.ne (i32.and (local.get $status) (i32.const 15)) (i32.const 1))
          (then unreachable))
        (i32.shr_u (local.get $status) (i32.const 4)))
      (func (export "run") (result i32)
        (local $target i32) (local $timer i32) (local $set i32) (local $event i32)
        (local.set $target (call $handle (call $target)))
        (call $ready)
        (local.set $timer (call $handle (call $sleep (i64.const {{GRACE_MS}}))))
        (local.set $set (call $new))
        (call $join (local.get $target) (local.get $set))
        (call $join (local.get $timer) (local.get $set))
        (call $trace (i32.const 10))
        ;; BLOCKED means resolution must be awaited on the original handle.
        ;; It does not permit dropping the handle or issuing another cancel.
        (if (i32.ne (call $cancel (local.get $target)) (i32.const -1))
          (then unreachable))
        (call $trace (i32.const 40))
        (loop $wait
          (local.set $event (call $wait (local.get $set) (i32.const 0)))
          (if (i32.ne (local.get $event) (i32.const 1)) (then unreachable))
          (br_if $wait (i32.lt_u (i32.load (i32.const 4)) (i32.const 2)))
          (if (i32.eq (i32.load (i32.const 0)) (local.get $timer))
            (then
              (call $trace (i32.const 70))
              ;; Qualification only: stop the whole execution, never return a
              ;; recoverable step error while its callee is still unresolved.
              unreachable))
          (if (i32.ne (i32.load (i32.const 0)) (local.get $target)) (then unreachable))
          (if (i32.ne (i32.load (i32.const 4)) (i32.const {{RESOLUTION}})) (then unreachable)))
        (call $drop (local.get $target))
        ;; Cancel the generous success-case timer rather than racing cleanup
        ;; against a short fixture deadline. Resolve this host subtask too.
        (if (i32.ne (call $cancel (local.get $timer)) (i32.const -1))
          (then unreachable))
        (loop $timer
          (if (i32.ne (call $wait (local.get $set) (i32.const 0)) (i32.const 1)) (then unreachable))
          (br_if $timer (i32.lt_u (i32.load (i32.const 4)) (i32.const 2)))
          (if (i32.ne (i32.load (i32.const 0)) (local.get $timer)) (then unreachable))
          (if (i32.ne (i32.load (i32.const 4)) (i32.const 4)) (then unreachable)))
        (call $drop (local.get $timer))
        (call $drop-set (local.get $set))
        (call $trace (i32.const 60))
        (i32.const 99)))
    (core instance $code (instantiate $code
      (with "m" (instance $memory))
      (with "h" (instance
        (export "target" (func $target)) (export "ready" (func $ready))
        (export "sleep" (func $sleep)) (export "trace" (func $trace))
        (export "cancel" (func $cancel)) (export "drop" (func $drop))
        (export "new" (func $new)) (export "join" (func $join))
        (export "wait" (func $wait)) (export "drop-set" (func $drop-set))))))
    (func (export "run") async (result u32) (canon lift (core func $code "run"))))
  (instance $workflow (instantiate $workflow
    (with "target" (func $agent "run")) (with "ready" (func $ready))
    (with "sleep" (func $timers "sleep")) (with "trace" (func $trace))))
  (export "run" (func $workflow "run")))
