;; Async-typed synchronous lift, with standard cancellable waits. The emitted
;; workflow compiler can retain its structured call stack: event 6 is delivered
;; at a wait, so it can clean up nested calls and return normally to its parent.
;; There is no callback, async-stackful lift, or optional async-cancel builtin.
(component $agent
  (import "request" (func $request async (result u32)))
  (import "trace" (func $trace (param "event" u32)))
  (core module $memory (memory (export "memory") 1))
  (core instance $memory (instantiate $memory))
  (core func $request (canon lower (func $request) async (memory $memory "memory")))
  (core func $trace (canon lower (func $trace)))
  (core func $new (canon waitable-set.new))
  (core func $join (canon waitable.join))
  (core func $wait (canon waitable-set.wait cancellable (memory $memory "memory")))
  (core func $cancel (canon subtask.cancel))
  (core func $drop (canon subtask.drop))
  (core func $drop-set (canon waitable-set.drop))
  (core module $code
    (import "m" "memory" (memory 1))
    (import "h" "request" (func $request (param i32) (result i32)))
    (import "h" "trace" (func $trace (param i32)))
    (import "h" "new" (func $new (result i32)))
    (import "h" "join" (func $join (param i32 i32)))
    (import "h" "wait" (func $wait (param i32 i32) (result i32)))
    (import "h" "cancel" (func $cancel (param i32) (result i32)))
    (import "h" "drop" (func $drop (param i32)))
    (import "h" "drop-set" (func $drop-set (param i32)))
    (global $calls (mut i32) (i32.const 0))
    (func (export "run") (result i32) (local $status i32) (local $handle i32) (local $set i32) (local $event i32)
      (global.set $calls (i32.add (global.get $calls) (i32.const 1)))
      (local.set $status (call $request (i32.const 0)))
      (if (i32.eq (i32.and (local.get $status) (i32.const 15)) (i32.const 2))
        (then (return (i32.add (i32.load (i32.const 0)) (global.get $calls)))))
      (local.set $handle (i32.shr_u (local.get $status) (i32.const 4)))
      (local.set $set (call $new))
      (call $join (local.get $handle) (local.get $set))
      (local.set $event (call $wait (local.get $set) (i32.const 16)))
      (if (i32.eq (local.get $event) (i32.const 6))
        (then
          (call $trace (i32.const 30))
          (call $join (local.get $handle) (i32.const 0))
          (if (i32.ne (call $cancel (local.get $handle)) (i32.const 4)) (then unreachable))
          (call $drop (local.get $handle))
          (call $drop-set (local.get $set))
          (call $trace (i32.const 50))
          (return (i32.const 123))))
      (if (i32.ne (local.get $event) (i32.const 1)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 20)) (i32.const 2)) (then unreachable))
      (call $drop (local.get $handle))
      (call $drop-set (local.get $set))
      (i32.add (i32.load (i32.const 0)) (global.get $calls))))
  (core instance $code (instantiate $code
    (with "m" (instance $memory))
    (with "h" (instance
      (export "request" (func $request)) (export "trace" (func $trace))
      (export "new" (func $new)) (export "join" (func $join))
      (export "wait" (func $wait)) (export "cancel" (func $cancel))
      (export "drop" (func $drop)) (export "drop-set" (func $drop-set))))))
  (func (export "run") async (result u32) (canon lift (core func $code "run"))))
