;; Appended to the shared callback-Agent fixture. This parent uses the current
;; production ABI, including synchronous subtask.cancel, and exports lifecycle.
  (component $workflow
    (import "target" (func $target async))
    (import "ready" (func $ready async))
    (import "alarm" (func $alarm async (param "ms" u64)))
    (import "sleep" (func $sleep async (param "ms" u64)))
    (import "trace" (func $trace (param "event" u32)))
    (core module $memory
      (memory (export "memory") 1)
      (global $heap (mut i32) (i32.const 8192))
      (func (export "realloc") (param i32 i32 i32) (param $size i32) (result i32) (local $p i32)
        (local.set $p (global.get $heap))
        (global.set $heap (i32.add (global.get $heap) (local.get $size)))
        (local.get $p)))
    (core instance $memory (instantiate $memory))
    (core func $target (canon lower (func $target) async))
    (core func $ready (canon lower (func $ready)))
    (core func $alarm (canon lower (func $alarm) async))
    (core func $sleep (canon lower (func $sleep)))
    (core func $trace (canon lower (func $trace)))
    (core func $cancel (canon subtask.cancel))
    (core func $drop (canon subtask.drop))
    (core module $code
      (import "m" "memory" (memory 1))
      (import "h" "target" (func $target (result i32)))
      (import "h" "ready" (func $ready))
      (import "h" "alarm" (func $alarm (param i64) (result i32)))
      (import "h" "sleep" (func $sleep (param i64)))
      (import "h" "trace" (func $trace (param i32)))
      (import "h" "cancel" (func $cancel (param i32) (result i32)))
      (import "h" "drop" (func $drop (param i32)))
      (func $handle (param $status i32) (result i32)
        (if (i32.ne (i32.and (local.get $status) (i32.const 15)) (i32.const 1)) (then unreachable))
        (i32.shr_u (local.get $status) (i32.const 4)))
      (data (i32.const 3500) "42")
      (func (export "invoke") (param i32 i32) (result i32)
        (local $target i32) (local $alarm i32)
        (local.set $alarm (call $handle (call $alarm (i64.const 500))))
        (local.set $target (call $handle (call $target)))
        (call $ready)
        (call $trace (i32.const 10))
        (if (i32.ne (call $cancel (local.get $target)) (i32.const 4)) (then unreachable))
        (call $drop (local.get $target))
        (call $trace (i32.const 40))
        (if (i32.ne (call $cancel (local.get $alarm)) (i32.const 4)) (then unreachable))
        (call $drop (local.get $alarm))
        ;; Advance past the disposed alarm's deadline in this same Store.
        (call $sleep (i64.const 600))
        (call $trace (i32.const 60))
        (i32.store (i32.const 2060) (i32.const 3500))
        (i32.store (i32.const 2064) (i32.const 2))
        (i32.const 2048)))
    (core instance $code (instantiate $code
      (with "m" (instance $memory))
      (with "h" (instance
        (export "target" (func $target)) (export "ready" (func $ready))
        (export "alarm" (func $alarm)) (export "sleep" (func $sleep))
        (export "trace" (func $trace)) (export "cancel" (func $cancel)) (export "drop" (func $drop))))))
    (type $error (record (field "code" string) (field "message" string) (field "category" string)
      (field "severity" string) (field "retryable" bool) (field "retry-after-ms" (option u64))
      (field "attributes" (option string))))
    (type $signal (record (field "checkpoint-id" string) (field "deadline-ms" (option u64))))
    (type $wake (variant (case "at" u64) (case "on-signal" $signal) (case "on-resume")))
    (type $outcome (variant (case "completed" (list u8)) (case "suspended" (list $wake))))
    (func $invoke async (param "input" (list u8)) (result (result $outcome (error $error)))
      (canon lift (core func $code "invoke") (memory $memory "memory") (realloc (func $memory "realloc"))))
    (instance $lifecycle
      (export "error-info" (type $error)) (export "signal-wait" (type $signal))
      (export "wake" (type $wake)) (export "outcome" (type $outcome)) (export "invoke" (func $invoke)))
    (export "runtara:workflow-lifecycle/lifecycle@0.2.0" (instance $lifecycle)))
  (instance $workflow (instantiate $workflow
    (with "target" (func $agent "run")) (with "ready" (func $ready))
    (with "alarm" (func $timers "abort-after")) (with "sleep" (func $timers "sleep"))
    (with "trace" (func $trace))))
  (alias export $workflow "runtara:workflow-lifecycle/lifecycle@0.2.0" (instance $lifecycle))
  (export "runtara:workflow-lifecycle/lifecycle@0.2.0" (instance $lifecycle)))
