;; A standard composition: all components live in the same Store. Only test I/O,
;; signal delivery and observation are host imports; cancellation happens in WASM.
(component
  (import "request" (func $request async (result u32)))
  (import "sibling" (func $sibling async (result u32)))
  (import "signal" (func $signal async))
  (import "trace" (func $trace (param "event" u32)))

  (component $agent
    (import "request" (func $request async (result u32)))
    (import "trace" (func $trace (param "event" u32)))
    (core module $memory (memory (export "memory") 1))
    (core instance $memory (instantiate $memory))
    (core func $request (canon lower (func $request) async (memory $memory "memory")))
    (core func $trace (canon lower (func $trace)))
    (core func $new (canon waitable-set.new))
    (core func $join (canon waitable.join))
    (core func $drop-set (canon waitable-set.drop))
    (core func $cancel (canon subtask.cancel))
    (core func $drop (canon subtask.drop))
    (core func $return (canon task.return (result u32)))
    (core func $cancelled (canon task.cancel))
    (core module $code
      (import "m" "memory" (memory 1))
      (import "h" "request" (func $request (param i32) (result i32)))
      (import "h" "trace" (func $trace (param i32)))
      (import "h" "new" (func $new (result i32)))
      (import "h" "join" (func $join (param i32 i32)))
      (import "h" "drop-set" (func $drop-set (param i32)))
      (import "h" "cancel" (func $cancel (param i32) (result i32)))
      (import "h" "drop" (func $drop (param i32)))
      (import "h" "return" (func $return (param i32)))
      (import "h" "cancelled" (func $cancelled))
      (global $handle (mut i32) (i32.const 0))
      (global $set (mut i32) (i32.const 0))
      (global $calls (mut i32) (i32.const 0))
      (func (export "run") (result i32) (local $status i32)
        (global.set $calls (i32.add (global.get $calls) (i32.const 1)))
        (local.set $status (call $request (i32.const 0)))
        (if (i32.eq (i32.and (local.get $status) (i32.const 15)) (i32.const 2))
          (then
            (call $return (i32.add (i32.load (i32.const 0)) (global.get $calls)))
            (return (i32.const 0))))
        (global.set $handle (i32.shr_u (local.get $status) (i32.const 4)))
        (global.set $set (call $new))
        (call $join (global.get $handle) (global.get $set))
        (i32.or (i32.shl (global.get $set) (i32.const 4)) (i32.const 2)))
      (func (export "callback") (param $event i32) (param $handle i32) (param $status i32) (result i32)
        (if (i32.eq (local.get $event) (i32.const 6))
          (then
            (call $trace (i32.const 30))
            (call $join (global.get $handle) (i32.const 0))
            ;; Drop cannot precede resolution. Cancellation synchronously waits
            ;; for the pending host future to be destroyed by the engine.
            (if (i32.ne (call $cancel (global.get $handle)) (i32.const 4))
              (then unreachable))
            (call $drop (global.get $handle))
            (call $drop-set (global.get $set))
            (call $trace (i32.const 50))
            (call $cancelled)
            (return (i32.const 0))))
        (if (i32.ne (local.get $event) (i32.const 1)) (then unreachable))
        (if (i32.ne (local.get $status) (i32.const 2)) (then unreachable))
        (call $drop (local.get $handle))
        (call $drop-set (global.get $set))
        (call $return (i32.add (i32.load (i32.const 0)) (global.get $calls)))
        (i32.const 0)))
    (core instance $code (instantiate $code
      (with "m" (instance $memory))
      (with "h" (instance
        (export "request" (func $request)) (export "trace" (func $trace))
        (export "new" (func $new)) (export "join" (func $join))
        (export "drop-set" (func $drop-set)) (export "cancel" (func $cancel))
        (export "drop" (func $drop)) (export "return" (func $return))
        (export "cancelled" (func $cancelled))))))
    (func (export "run") async (result u32)
      (canon lift (core func $code "run") async (callback (func $code "callback")))))

  (instance $target (instantiate $agent
    (with "request" (func $request)) (with "trace" (func $trace))))
  (instance $sibling (instantiate $agent
    (with "request" (func $sibling)) (with "trace" (func $trace))))
  (component $workflow
    (import "target" (func $target async (result u32)))
    (import "sibling" (func $sibling async (result u32)))
    (import "signal" (func $signal async))
    (import "trace" (func $trace (param "event" u32)))
  (core module $memory (memory (export "memory") 1))
  (core instance $memory (instantiate $memory))
  (core func $target (canon lower (func $target) async (memory $memory "memory")))
  (core func $sibling (canon lower (func $sibling) async (memory $memory "memory")))
  (core func $signal (canon lower (func $signal)))
  (core func $trace (canon lower (func $trace)))
  (core func $cancel (canon subtask.cancel))
  (core func $drop (canon subtask.drop))
  (core func $new (canon waitable-set.new))
  (core func $join (canon waitable.join))
  (core func $wait (canon waitable-set.wait (memory $memory "memory")))
  (core func $drop-set (canon waitable-set.drop))
  (core module $parent
    (import "m" "memory" (memory 1))
    (import "h" "target" (func $target (param i32) (result i32)))
    (import "h" "sibling" (func $sibling (param i32) (result i32)))
    (import "h" "signal" (func $signal))
    (import "h" "trace" (func $trace (param i32)))
    (import "h" "cancel" (func $cancel (param i32) (result i32)))
    (import "h" "drop" (func $drop (param i32)))
    (import "h" "new" (func $new (result i32)))
    (import "h" "join" (func $join (param i32 i32)))
    (import "h" "wait" (func $wait (param i32 i32) (result i32)))
    (import "h" "drop-set" (func $drop-set (param i32)))
    (func $resolve (param $status i32) (local $handle i32) (local $set i32)
      (if (i32.eq (i32.and (local.get $status) (i32.const 15)) (i32.const 2)) (then return))
      (local.set $handle (i32.shr_u (local.get $status) (i32.const 4)))
      (local.set $set (call $new))
      (call $join (local.get $handle) (local.get $set))
      (if (i32.ne (call $wait (local.get $set) (i32.const 32)) (i32.const 1)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 36)) (i32.const 2)) (then unreachable))
      (call $drop (local.get $handle))
      (call $drop-set (local.get $set)))
    (func (export "run") (result i32) (local $target i32) (local $sibling i32)
      (call $trace (i32.const 10))
      (local.set $target (call $target (i32.const 0)))
      (call $trace (i32.const 11))
      (local.set $sibling (call $sibling (i32.const 4)))
      (call $trace (i32.const 12))
      ;; The fixture signal is delivered only once both I/O operations started.
      (call $signal)
      (call $trace (i32.const 13))
      (if (i32.ne (i32.and (local.get $target) (i32.const 15)) (i32.const 1)) (then unreachable))
      (local.set $target (i32.shr_u (local.get $target) (i32.const 4)))
      (if (i32.ne (call $cancel (local.get $target)) (i32.const 4)) (then unreachable))
      (call $drop (local.get $target))
      (call $trace (i32.const 60))
      (call $resolve (local.get $sibling))
      (if (i32.ne (i32.load (i32.const 4)) (i32.const 8)) (then unreachable))
      ;; Reuse the cancelled component instance. Its call counter must be 2.
      (call $resolve (call $target (i32.const 8)))
      (if (i32.ne (i32.load (i32.const 8)) (i32.const 44)) (then unreachable))
      (i32.const 99)))
  (core instance $parent (instantiate $parent
    (with "m" (instance $memory))
    (with "h" (instance
      (export "target" (func $target)) (export "sibling" (func $sibling))
      (export "signal" (func $signal)) (export "trace" (func $trace))
      (export "cancel" (func $cancel)) (export "drop" (func $drop))
      (export "new" (func $new)) (export "join" (func $join))
      (export "wait" (func $wait)) (export "drop-set" (func $drop-set))))))
  (func (export "run") async (result u32) (canon lift (core func $parent "run"))))
  (instance $workflow (instantiate $workflow
    (with "target" (func $target "run"))
    (with "sibling" (func $sibling "run"))
    (with "signal" (func $signal))
    (with "trace" (func $trace))))
  (export "run" (func $workflow "run")))
