;; Deadline-selection prototype using standard Component Model subtasks.
;; The fixture barrier only controls readiness; guest code selects the outcome.
(component
  (import "runtara:agent-{{AGENT}}/capabilities@0.4.0" (instance $http
    (type $error-def (record (field "code" string) (field "message" string)
      (field "category" string) (field "severity" string) (field "retryable" bool)
      (field "retry-after-ms" (option u64)) (field "attributes" (option string))))
    (export "error-info" (type $error (eq $error-def)))
    (export "invoke" (func async (param "capability-id" string) (param "input" (list u8))
      (result (result (list u8) (error $error)))))))
  (import "runtara:host-io/timers@0.1.0" (instance $timers
    (export "sleep" (func async (param "ms" u64)))))
  (import "ready-barrier" (func $barrier async))
  (import "sibling" (func $sibling async (result u32)))
  (core module $memory
    (memory (export "memory") {{PAGES}})
    (global $heap (mut i32) (i32.const {{HEAP}}))
    (func (export "realloc") (param i32 i32 i32) (param $size i32) (result i32) (local $p i32)
      (local.set $p (global.get $heap))
      (global.set $heap (i32.and (i32.add (i32.add (global.get $heap) (local.get $size)) (i32.const 15)) (i32.const -16)))
      (local.get $p)))
  (core instance $memory (instantiate $memory))
  (core func $invoke (canon lower (func $http "invoke") async
    (memory $memory "memory") (realloc (func $memory "realloc"))))
  (core func $barrier (canon lower (func $barrier)))
  (core func $sibling (canon lower (func $sibling) async (memory $memory "memory")))
  (core func $sleep (canon lower (func $timers "sleep") async))
  (core func $poll (canon waitable-set.poll (memory $memory "memory")))
  (core func $cancel (canon subtask.cancel))
  (core func $drop (canon subtask.drop))
  (core func $new (canon waitable-set.new))
  (core func $join (canon waitable.join))
  (core func $wait (canon waitable-set.wait (memory $memory "memory")))
  (core func $drop-set (canon waitable-set.drop))
  (core module $code
    (import "m" "memory" (memory 2))
    (import "h" "invoke" (func $invoke (param i32 i32 i32 i32 i32) (result i32)))
    (import "h" "barrier" (func $barrier))
    (import "h" "sibling" (func $sibling (param i32) (result i32)))
    (import "h" "sleep" (func $sleep (param i64) (result i32)))
    (import "h" "poll" (func $poll (param i32 i32) (result i32)))
    (import "h" "cancel" (func $cancel (param i32) (result i32)))
    (import "h" "drop" (func $drop (param i32)))
    (import "h" "new" (func $new (result i32)))
    (import "h" "join" (func $join (param i32 i32)))
    (import "h" "wait" (func $wait (param i32 i32) (result i32)))
    (import "h" "drop-set" (func $drop-set (param i32)))
    (data (i32.const 1024) "{{CAPABILITY}}")
    (data (i32.const 1536) "{{SECOND_CAPABILITY}}")
    (data (i32.const 2048) "{{INPUT}}")
    (data (i32.const {{SECOND_INPUT_OFFSET}}) "{{SECOND_INPUT}}")
    (func $resolve (param $status i32) (local $handle i32) (local $set i32)
      (if (i32.eq (i32.and (local.get $status) (i32.const 15)) (i32.const 2)) (then return))
      (local.set $handle (i32.shr_u (local.get $status) (i32.const 4)))
      (local.set $set (call $new))
      (call $join (local.get $handle) (local.get $set))
      (if (i32.ne (call $wait (local.get $set) (i32.const 160)) (i32.const 1)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 164)) (i32.const 2)) (then unreachable))
      (call $drop (local.get $handle))
      (call $drop-set (local.get $set)))
    (global $target-handle (mut i32) (i32.const 0))
    (global $timer-handle (mut i32) (i32.const 0))
    (global $ready (mut i32) (i32.const 0))
    (global $timed-out (mut i32) (i32.const 0))
    (global $resolution (mut i32) (i32.const 0))
    (func (export "timed-out") (result i32) (global.get $timed-out))
    (func (export "ready-mask") (result i32) (global.get $ready))
    (func (export "cancel-resolution") (result i32) (global.get $resolution))
    (func $cancel-drop (param $handle i32) (result i32) (local $status i32)
      (call $join (local.get $handle) (i32.const 0))
      (local.set $status (call $cancel (local.get $handle)))
      (if (i32.or (i32.lt_u (local.get $status) (i32.const 2))
                  (i32.gt_u (local.get $status) (i32.const 4))) (then unreachable))
      (call $drop (local.get $handle))
      (local.get $status))
    (func $observe (param $event i32) (local $handle i32)
      (if (i32.eqz (local.get $event)) (then return))
      (if (i32.ne (local.get $event) (i32.const 1)) (then unreachable))
      ;; Starting/started notifications are not completed results.
      (if (i32.lt_u (i32.load (i32.const 164)) (i32.const 2)) (then return))
      (if (i32.ne (i32.load (i32.const 164)) (i32.const 2)) (then unreachable))
      (local.set $handle (i32.load (i32.const 160)))
      (if (i32.eq (local.get $handle) (global.get $target-handle))
        (then
          (global.set $ready (i32.or (global.get $ready) (i32.const 1)))
          (global.set $target-handle (i32.const 0)))
        (else
          (if (i32.ne (local.get $handle) (global.get $timer-handle)) (then unreachable))
          (global.set $ready (i32.or (global.get $ready) (i32.const 2)))
          (global.set $timer-handle (i32.const 0))))
      (call $drop (local.get $handle)))
    (func $race (param $target i32) (param $timer i32) (local $set i32) (local $event i32)
      (global.set $ready (i32.const 0))
      (global.set $resolution (i32.const 0))
      (global.set $target-handle (i32.const 0))
      (global.set $timer-handle (i32.const 0))
      (local.set $set (call $new))
      (if (i32.eq (i32.and (local.get $target) (i32.const 15)) (i32.const 2))
        (then (global.set $ready (i32.const 1)))
        (else
          (global.set $target-handle (i32.shr_u (local.get $target) (i32.const 4)))
          (call $join (global.get $target-handle) (local.get $set))))
      (if (i32.eq (i32.and (local.get $timer) (i32.const 15)) (i32.const 2))
        (then (global.set $ready (i32.or (global.get $ready) (i32.const 2))))
        (else
          (global.set $timer-handle (i32.shr_u (local.get $timer) (i32.const 4)))
          (call $join (global.get $timer-handle) (local.get $set))))
      ;; Test readiness barrier; it cannot choose timeout or cancel anything.
      (call $barrier)
      (block $selected
        (loop
          ;; Drain ready events, including nonterminal state notifications.
          ;; Completion wins when observed in the same ready set as expiry.
          (block $drained
            (loop $drain
              (local.set $event (call $poll (local.get $set) (i32.const 160)))
              (br_if $drained (i32.eqz (local.get $event)))
              (call $observe (local.get $event))
              (br $drain)))
          (br_if $selected (global.get $ready))
          (call $observe (call $wait (local.get $set) (i32.const 160)))
          (br 0)))
      (global.set $timed-out (i32.eqz (i32.and (global.get $ready) (i32.const 1))))
      (if (global.get $timed-out)
        (then
          ;; The chosen deadline is final even if cancel resolves as RETURNED.
          ;; Cleanup may finish normally; that does not accept a late result.
          (global.set $resolution (call $cancel-drop (global.get $target-handle)))
          (global.set $target-handle (i32.const 0)))
        (else
          (if (global.get $timer-handle)
            (then
              (drop (call $cancel-drop (global.get $timer-handle)))
              (global.set $timer-handle (i32.const 0))))))
      (call $drop-set (local.get $set)))
    (func (export "run") (result i32) (local $target i32) (local $sibling i32)
      (local.set $target (call $invoke (i32.const 1024) (i32.const {{CAPABILITY_LEN}}) (i32.const 2048) (i32.const {{INPUT_LEN}}) (i32.const 0)))
      (local.set $sibling (call $sibling (i32.const 128)))
      (call $race (local.get $target) (call $sleep (i64.const {{TIMEOUT}})))
      (if (i32.eqz (global.get $timed-out))
        (then (if (i32.ne (i32.load8_u (i32.const 0)) (i32.const 0)) (then unreachable))))
      (call $resolve (local.get $sibling))
      (if (i32.ne (i32.load (i32.const 128)) (i32.const 7)) (then unreachable))
      ;; A second capability call in the same real Agent instance must still work.
      (call $resolve (call $invoke (i32.const 1536) (i32.const {{SECOND_CAPABILITY_LEN}}) (i32.const {{SECOND_INPUT_OFFSET}}) (i32.const {{SECOND_INPUT_LEN}}) (i32.const 64)))
      ;; Return the actual JSON success bytes to the native assertions.
      (if (i32.ne (i32.load8_u (i32.const 64)) (i32.const 0)) (then unreachable))
      (i32.store (i32.const 96) (i32.load (i32.const 72)))
      (i32.store (i32.const 100) (i32.load (i32.const 76)))
      (i32.const 96)))
  (core instance $code (instantiate $code
    (with "m" (instance $memory))
    (with "h" (instance
      (export "sleep" (func $sleep)) (export "poll" (func $poll))
      (export "invoke" (func $invoke)) (export "barrier" (func $barrier))
      (export "sibling" (func $sibling)) (export "cancel" (func $cancel))
      (export "drop" (func $drop)) (export "new" (func $new))
      (export "join" (func $join)) (export "wait" (func $wait))
      (export "drop-set" (func $drop-set))))))
  (func (export "timed-out") (result u32) (canon lift (core func $code "timed-out")))
  (func (export "ready-mask") (result u32) (canon lift (core func $code "ready-mask")))
  (func (export "cancel-resolution") (result u32) (canon lift (core func $code "cancel-resolution")))
  (func (export "run") async (result (list u8))
    (canon lift (core func $code "run") (memory $memory "memory") (realloc (func $memory "realloc")))))
