(component
  (import "runtara:agent-http/capabilities@0.4.0" (instance $http
    (type $error-def (record (field "code" string) (field "message" string)
      (field "category" string) (field "severity" string) (field "retryable" bool)
      (field "retry-after-ms" (option u64)) (field "attributes" (option string))))
    (export "error-info" (type $error (eq $error-def)))
    (export "invoke" (func async (param "capability-id" string) (param "input" (list u8))
      (result (result (list u8) (error $error)))))))
  (import "signal" (func $signal async))
  (import "sibling" (func $sibling async (result u32)))
  (core module $memory
    (memory (export "memory") 2)
    (global $heap (mut i32) (i32.const 32768))
    (func (export "realloc") (param i32 i32 i32) (param $size i32) (result i32) (local $p i32)
      (local.set $p (global.get $heap))
      (global.set $heap (i32.and (i32.add (i32.add (global.get $heap) (local.get $size)) (i32.const 15)) (i32.const -16)))
      (local.get $p)))
  (core instance $memory (instantiate $memory))
  (core func $invoke (canon lower (func $http "invoke") async
    (memory $memory "memory") (realloc (func $memory "realloc"))))
  (core func $signal (canon lower (func $signal)))
  (core func $sibling (canon lower (func $sibling) async (memory $memory "memory")))
  (core func $cancel (canon subtask.cancel))
  (core func $drop (canon subtask.drop))
  (core func $new (canon waitable-set.new))
  (core func $join (canon waitable.join))
  (core func $wait (canon waitable-set.wait (memory $memory "memory")))
  (core func $drop-set (canon waitable-set.drop))
  (core module $code
    (import "m" "memory" (memory 2))
    (import "h" "invoke" (func $invoke (param i32 i32 i32 i32 i32) (result i32)))
    (import "h" "signal" (func $signal))
    (import "h" "sibling" (func $sibling (param i32) (result i32)))
    (import "h" "cancel" (func $cancel (param i32) (result i32)))
    (import "h" "drop" (func $drop (param i32)))
    (import "h" "new" (func $new (result i32)))
    (import "h" "join" (func $join (param i32 i32)))
    (import "h" "wait" (func $wait (param i32 i32) (result i32)))
    (import "h" "drop-set" (func $drop-set (param i32)))
    (data (i32.const 1024) "http-request")
    (data (i32.const 2048) "{{INPUT}}")
    (data (i32.const 8192) "{{SECOND_INPUT}}")
    (func $resolve (param $status i32) (local $handle i32) (local $set i32)
      (if (i32.eq (i32.and (local.get $status) (i32.const 15)) (i32.const 2)) (then return))
      (local.set $handle (i32.shr_u (local.get $status) (i32.const 4)))
      (local.set $set (call $new))
      (call $join (local.get $handle) (local.get $set))
      (if (i32.ne (call $wait (local.get $set) (i32.const 160)) (i32.const 1)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 164)) (i32.const 2)) (then unreachable))
      (call $drop (local.get $handle))
      (call $drop-set (local.get $set)))
    (func (export "run") (result i32) (local $target i32) (local $sibling i32)
      (local.set $target (call $invoke (i32.const 1024) (i32.const 12) (i32.const 2048) (i32.const {{INPUT_LEN}}) (i32.const 0)))
      (if (i32.ne (i32.and (local.get $target) (i32.const 15)) (i32.const 1)) (then unreachable))
      (local.set $sibling (call $sibling (i32.const 128)))
      (call $signal)
      (local.set $target (i32.shr_u (local.get $target) (i32.const 4)))
      (if (i32.ne (call $cancel (local.get $target)) (i32.const 4)) (then unreachable))
      (call $drop (local.get $target))
      (call $resolve (local.get $sibling))
      (if (i32.ne (i32.load (i32.const 128)) (i32.const 7)) (then unreachable))
      ;; A second HTTP call in the same real Agent instance must still work.
      (call $resolve (call $invoke (i32.const 1024) (i32.const 12) (i32.const 8192) (i32.const {{SECOND_INPUT_LEN}}) (i32.const 64)))
      ;; Return the actual JSON success bytes to the native assertions.
      (if (i32.ne (i32.load8_u (i32.const 64)) (i32.const 0)) (then unreachable))
      (i32.store (i32.const 96) (i32.load (i32.const 72)))
      (i32.store (i32.const 100) (i32.load (i32.const 76)))
      (i32.const 96)))
  (core instance $code (instantiate $code
    (with "m" (instance $memory))
    (with "h" (instance
      (export "invoke" (func $invoke)) (export "signal" (func $signal))
      (export "sibling" (func $sibling)) (export "cancel" (func $cancel))
      (export "drop" (func $drop)) (export "new" (func $new))
      (export "join" (func $join)) (export "wait" (func $wait))
      (export "drop-set" (func $drop-set))))))
  (func (export "run") async (result (list u8))
    (canon lift (core func $code "run") (memory $memory "memory") (realloc (func $memory "realloc")))))
