;; A component-level import of the canonical execution ABI. The test WIT parser
;; and Wasmtime linker both validate the resource/async/value signatures.
(import "runtara:workflow-execution/tasks@0.1.0" (instance $tasks
  (export "task" (type $task (sub resource)))
  (type $error-info-def (record (field "code" string) (field "message" string)
    (field "category" string) (field "severity" string) (field "retryable" bool)
    (field "retry-after-ms" (option u64)) (field "attributes" (option string))))
  (export "error-info" (type $error-info (eq $error-info-def)))
  (type $signal-def (record (field "checkpoint-id" string) (field "deadline-ms" (option u64))))
  (export "signal-wait" (type $signal (eq $signal-def)))
  (type $wake-def (variant (case "at" u64) (case "on-signal" $signal) (case "on-resume")))
  (export "wake" (type $wake (eq $wake-def)))
  (type $entry-def (variant (case "capability" string) (case "workflow")))
  (export "entry" (type $entry (eq $entry-def)))
  (type $context-def (record (field "path" string) (field "attempt" u64)))
  (export "invocation-context" (type $context (eq $context-def)))
  (type $error-def (enum "unavailable" "closed" "capacity" "invalid-binding" "invalid-context" "invalid-task" "worker-lost"))
  (export "execution-error" (type $error (eq $error-def)))
  (type $cancel-def (enum "requested" "already-requested" "already-terminal"))
  (export "cancel-status" (type $cancel (eq $cancel-def)))
  (type $outcome-def (variant (case "completed" (list u8)) (case "failed" $error-info)
    (case "suspended" (list $wake)) (case "cancelled") (case "timed-out") (case "trapped" string)))
  (export "task-outcome" (type $outcome (eq $outcome-def)))
  (export "start" (func (param "binding" string) (param "entry" $entry) (param "input" (list u8)) (param "context" $context)
    (result (result (own $task) (error $error)))))
  (export "request-cancel" (func (param "handle" (borrow $task)) (result (result $cancel (error $error)))))
  (export "join" (func async (param "handle" (borrow $task)) (result (result $outcome (error $error)))))
  (export "release" (func async (param "handle" (borrow $task)) (result (result (error $error)))))
))
