(component
  {{INTERFACE}}
  (import "wait-started" (func $wait-started async))
  (alias export $tasks "task" (type $task))
  (alias export $tasks "start" (func $start))
  (alias export $tasks "request-cancel" (func $cancel))
  (alias export $tasks "join" (func $join))
  (alias export $tasks "release" (func $release))
  (core module $mem
    (memory (export "memory") 4)
    (global $next (mut i32) (i32.const 8192))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $p i32)
      global.get $next local.set $p
      global.get $next local.get 3 i32.add i32.const 15 i32.add i32.const -16 i32.and global.set $next
      local.get $p))
  (core instance $mem (instantiate $mem))
  (core func $start (canon lower (func $start) (memory $mem "memory") (realloc (func $mem "realloc"))))
  (core func $cancel (canon lower (func $cancel) (memory $mem "memory")))
  (core func $join (canon lower (func $join) (memory $mem "memory") (realloc (func $mem "realloc"))))
  (core func $release (canon lower (func $release) (memory $mem "memory")))
  (core func $drop (canon resource.drop $task))
  (core func $wait (canon lower (func $wait-started)))
  (core module $code
    (import "mem" "memory" (memory 4))
    (import "host" "start" (func $start (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i64 i32)))
    (import "host" "cancel" (func $cancel (param i32 i32)))
    (import "host" "join" (func $join (param i32 i32)))
    (import "host" "release" (func $release (param i32 i32)))
    (import "host" "drop" (func $drop (param i32)))
    (import "host" "wait" (func $wait))
    (data (i32.const 1024) "child")
    (data (i32.const 1040) "pending")
    (data (i32.const 1056) "echo")
    (data (i32.const 1072) "parent/step")
    (data (i32.const 1096) "\09")
    (func (export "run") (result i32)
      (local $pending i32) (local $sibling i32)
      (call $start (i32.const 1024) (i32.const 5) (i32.const 0) (i32.const 1040) (i32.const 7)
        (i32.const 0) (i32.const 0) (i32.const 1072) (i32.const 11) (i64.const 7) (i32.const 64))
      (if (i32.load (i32.const 64)) (then unreachable))
      (local.set $pending (i32.load (i32.const 68)))
      call $wait
      {{EARLY_EXIT}}
      ;; Parent WASM chooses to run and join a sibling while the first child waits.
      (call $start (i32.const 1024) (i32.const 5) (i32.const 0) (i32.const 1056) (i32.const 4)
        (i32.const 1096) (i32.const 1) (i32.const 1072) (i32.const 11) (i64.const 8) (i32.const 96))
      (if (i32.load (i32.const 96)) (then unreachable))
      (local.set $sibling (i32.load (i32.const 100)))
      (call $join (local.get $sibling) (i32.const 256))
      (if (i32.load (i32.const 256)) (then unreachable))
      (if (i32.load (i32.const 264)) (then unreachable))
      (if (i32.ne (i32.load8_u (i32.load (i32.const 272))) (i32.const 9)) (then unreachable))
      (call $cancel (local.get $pending) (i32.const 128))
      (if (i32.load (i32.const 128)) (then unreachable))
      (call $join (local.get $pending) (i32.const 512))
      (if (i32.load (i32.const 512)) (then unreachable))
      (if (i32.ne (i32.load (i32.const 520)) (i32.const 3)) (then unreachable))
      (call $release (local.get $pending) (i32.const 144))
      (call $drop (local.get $pending))
      (call $release (local.get $sibling) (i32.const 144))
      (call $drop (local.get $sibling))
      ;; This recovery continuation is executed by the parent, not the host.
      i32.const 42))
  (core instance $host (export "start" (func $start)) (export "cancel" (func $cancel))
    (export "join" (func $join)) (export "release" (func $release)) (export "drop" (func $drop)) (export "wait" (func $wait)))
  (core instance $code (instantiate $code (with "mem" (instance $mem)) (with "host" (instance $host))))
  (func (export "run") async (result u32) (canon lift (core func $code "run"))))
