(component
  {{INTERFACE}}
  (alias export $tasks "task" (type $task))
  (alias export $tasks "error-info" (type $error-info))
  (alias export $tasks "signal-wait" (type $signal))
  (alias export $tasks "wake" (type $wake))
  (alias export $tasks "entry" (type $entry))
  (alias export $tasks "invocation-context" (type $context))
  (alias export $tasks "execution-error" (type $error))
  (alias export $tasks "cancel-status" (type $cancel-status))
  (alias export $tasks "task-outcome" (type $outcome))
  (alias export $tasks "start" (func $start))
  (alias export $tasks "request-cancel" (func $cancel))
  (alias export $tasks "join" (func $join))
  (alias export $tasks "release" (func $release))
  (core module $mem
    (memory (export "memory") 8)
    (global $next (mut i32) (i32.const 8192))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $p i32)
      global.get $next local.set $p
      global.get $next local.get 3 i32.add i32.const 15 i32.add i32.const -16 i32.and global.set $next
      local.get $p))
  (core instance $mem (instantiate $mem))
  (core func $start (canon lower (func $start) (memory $mem "memory") (realloc (func $mem "realloc"))))
  (core func $cancel (canon lower (func $cancel) (memory $mem "memory")))
  (core func $join (canon lower (func $join) (memory $mem "memory") (realloc (func $mem "realloc"))))
  (core func $release (canon lower (func $release) (memory $mem "memory")))
  (core func $drop (canon resource.drop $task))
  (core module $code
    (import "host" "drop" (func $drop (param i32)))
    (import "host" "start" (func $start (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i64 i32)))
    (import "host" "cancel" (func $cancel (param i32 i32)))
    (import "host" "join" (func $join (param i32 i32)))
    (import "host" "release" (func $release (param i32 i32)))
    (func (export "start") (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i64) (result i32)
      local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 local.get 8 local.get 9
      i32.const 2048 call $start i32.const 2048)
    (func (export "cancel") (param i32) (result i32)
      local.get 0 i32.const 2048 call $cancel local.get 0 call $drop i32.const 2048)
    (func (export "join") (param i32) (result i32)
      local.get 0 i32.const 2048 call $join local.get 0 call $drop i32.const 2048)
    (func (export "release") (param i32) (result i32)
      local.get 0 i32.const 2048 call $release local.get 0 call $drop i32.const 2048))
  (core instance $host (export "drop" (func $drop)) (export "start" (func $start)) (export "cancel" (func $cancel))
    (export "join" (func $join)) (export "release" (func $release)))
  (core instance $code (instantiate $code (with "host" (instance $host))))
  (func $start-out (param "binding" string) (param "entry" $entry) (param "input" (list u8)) (param "context" $context)
    (result (result (own $task) (error $error)))
    (canon lift (core func $code "start") (memory $mem "memory") (realloc (func $mem "realloc"))))
  (func $cancel-out (param "handle" (borrow $task)) (result (result $cancel-status (error $error)))
    (canon lift (core func $code "cancel") (memory $mem "memory")))
  (func $join-out async (param "handle" (borrow $task)) (result (result $outcome (error $error)))
    (canon lift (core func $code "join") (memory $mem "memory")))
  (func $release-out async (param "handle" (borrow $task)) (result (result (error $error)))
    (canon lift (core func $code "release") (memory $mem "memory")))
  (instance $api
    (export "task" (type $task)) (export "error-info" (type $error-info)) (export "signal-wait" (type $signal))
    (export "wake" (type $wake)) (export "entry" (type $entry)) (export "invocation-context" (type $context))
    (export "execution-error" (type $error)) (export "cancel-status" (type $cancel-status)) (export "task-outcome" (type $outcome))
    (export "start" (func $start-out)) (export "request-cancel" (func $cancel-out))
    (export "join" (func $join-out)) (export "release" (func $release-out)))
  (export "api" (instance $api)))
