// Copyright (C) 2025 SyncMyOrders Sp. z o.o.
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Component-facing artifacts for the direct workflow compiler.

use runtara_workflow_wit::{RUNTIME_PACKAGE, STDLIB_PACKAGE, WORKFLOW_WIT_VERSION};

/// Package name used by direct-emitted workflow logic components.
pub const DIRECT_WORKFLOW_LOGIC_PACKAGE: &str = "runtara:workflow-logic@0.1.0";

/// Direct component composition scaffolding emitted beside direct artifacts.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DirectComponentArtifacts {
    /// `wit/world.wit` for the workflow-logic component.
    pub world_wit: String,
    /// `workflow.wac` static composition script.
    pub wac_source: String,
    /// Stdlib component package to bind during static composition.
    pub stdlib_package: String,
    /// Runtime component package to bind during static composition.
    pub runtime_package: String,
}

/// Emit the direct workflow component scaffolding.
///
/// The current finish-only direct compiler writes a component-format metadata
/// envelope as `workflow.wasm`. These artifacts define the WIT/WAC contract the
/// executable component dispatcher will implement without changing the output
/// directory contract.
pub fn emit_direct_component_artifacts(agents: &[String]) -> DirectComponentArtifacts {
    DirectComponentArtifacts {
        world_wit: emit_world_wit(agents),
        wac_source: emit_wac(agents),
        stdlib_package: STDLIB_PACKAGE.to_string(),
        runtime_package: RUNTIME_PACKAGE.to_string(),
    }
}

fn emit_world_wit(agents: &[String]) -> String {
    let mut out = format!(
        "// Generated by runtara-workflows direct component scaffold.\n\
         package runtara:workflow@{WORKFLOW_WIT_VERSION};\n\
         \n\
         world workflow {{\n\
             import runtara:workflow-stdlib/json@{WORKFLOW_WIT_VERSION};\n\
             import runtara:workflow-runtime/runtime@{WORKFLOW_WIT_VERSION};\n",
    );
    for agent in agents {
        out.push_str(&format!(
            "    import runtara:agent-{agent}/capabilities@0.3.0;\n"
        ));
    }
    out.push_str("    include wasi:cli/command@0.2.3;\n");
    out.push_str("}\n");
    out
}

fn emit_wac(agents: &[String]) -> String {
    let mut out = format!(
        "// Generated by runtara-workflows direct component scaffold.\n\
         package runtara:workflow-instance@{WORKFLOW_WIT_VERSION};\n\
         \n\
         let workflow-stdlib = new runtara:workflow-stdlib {{ ... }};\n\
         let workflow-runtime = new runtara:workflow-runtime {{ ... }};\n",
    );

    for agent in agents {
        out.push_str(&format!(
            "let agent-{id} = new runtara:agent-{id} {{ ... }};\n",
            id = agent
        ));
    }

    out.push_str("\nlet wf = new runtara:workflow-logic {");
    out.push_str(" ...workflow-stdlib, ...workflow-runtime,");
    for agent in agents {
        out.push_str(&format!(" ...agent-{id},", id = agent));
    }
    out.push_str(" ... };\n\n");
    out.push_str("export wf...;\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn direct_world_imports_stdlib_runtime_and_wasi_run() {
        let artifacts = emit_direct_component_artifacts(&[]);

        assert!(
            artifacts
                .world_wit
                .contains("package runtara:workflow@0.1.0;")
        );
        assert!(
            artifacts
                .world_wit
                .contains("import runtara:workflow-stdlib/json@0.1.0;")
        );
        assert!(
            artifacts
                .world_wit
                .contains("import runtara:workflow-runtime/runtime@0.1.0;")
        );
        assert!(
            artifacts
                .world_wit
                .contains("include wasi:cli/command@0.2.3;")
        );
    }

    #[test]
    fn direct_wac_statically_composes_stdlib_runtime_and_agents() {
        let artifacts =
            emit_direct_component_artifacts(&["crypto".to_string(), "object-model".to_string()]);

        assert!(
            artifacts
                .wac_source
                .contains("let workflow-stdlib = new runtara:workflow-stdlib")
        );
        assert!(
            artifacts
                .wac_source
                .contains("let workflow-runtime = new runtara:workflow-runtime")
        );
        assert!(
            artifacts
                .wac_source
                .contains("let agent-crypto = new runtara:agent-crypto")
        );
        assert!(
            artifacts
                .wac_source
                .contains("let agent-object-model = new runtara:agent-object-model")
        );
        assert!(
            artifacts
                .wac_source
                .contains("...workflow-stdlib, ...workflow-runtime,")
        );
        assert!(artifacts.wac_source.contains("...agent-crypto,"));
        assert!(artifacts.wac_source.contains("...agent-object-model,"));
        assert!(artifacts.wac_source.contains("export wf...;"));
    }
}
