// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod runtara {
    pub mod agent {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct ErrorInfo {
                pub code: _rt::String,
                pub message: _rt::String,
                pub category: _rt::String,
                /// "transient" | "permanent"
                pub severity: _rt::String,
                /// "warning" | "error" | "critical"
                pub retryable: bool,
                pub retry_after_ms: Option<u64>,
                pub attributes: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for ErrorInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ErrorInfo")
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .field("category", &self.category)
                        .field("severity", &self.severity)
                        .field("retryable", &self.retryable)
                        .field("retry-after-ms", &self.retry_after_ms)
                        .field("attributes", &self.attributes)
                        .finish()
                }
            }
            impl ::core::fmt::Display for ErrorInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for ErrorInfo {}
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod runtara {
        pub mod agent_mailgun {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod capabilities {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ErrorInfo = super::super::super::super::runtara::agent::types::ErrorInfo;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_invoke_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let result2 = T::invoke(
                        _rt::string_lift(bytes0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::runtara::agent::types::ErrorInfo {
                                code: code5,
                                message: message5,
                                category: category5,
                                severity: severity5,
                                retryable: retryable5,
                                retry_after_ms: retry_after_ms5,
                                attributes: attributes5,
                            } = e;
                            let vec6 = (code5.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr3.add(8).cast::<*mut u8>() = ptr6.cast_mut();
                            let vec7 = (message5.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr3
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr3
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                            let vec8 = (category5.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr3
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr3
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                            let vec9 = (severity5.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *ptr3
                                .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *ptr3
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr9.cast_mut();
                            *ptr3
                                .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match retryable5 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            match retry_after_ms5 {
                                Some(e) => {
                                    *ptr3
                                        .add(16 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    *ptr3
                                        .add(24 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i64>() = _rt::as_i64(e);
                                }
                                None => {
                                    *ptr3
                                        .add(16 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match attributes5 {
                                Some(e) => {
                                    *ptr3
                                        .add(32 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec10 = (e.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *ptr3
                                        .add(32 + 10 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *ptr3
                                        .add(32 + 9 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                }
                                None => {
                                    *ptr3
                                        .add(32 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_invoke<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0.add(8).cast::<*mut u8>();
                            let l5 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                            let l6 = *arg0
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *arg0
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                            let l8 = *arg0
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l8, l9, 1);
                            let l10 = *arg0
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l11 = *arg0
                                .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l10, l11, 1);
                            let l12 = i32::from(
                                *arg0
                                    .add(32 + 8 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l12 {
                                0 => {}
                                _ => {
                                    let l13 = *arg0
                                        .add(32 + 9 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l14 = *arg0
                                        .add(32 + 10 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l13, l14, 1);
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    /// The connection (if any) is delivered inside `input` under `_connection`;
                    /// there is no out-of-band connection argument. A connection is an opaque
                    /// id — the host proxy resolves credentials by (id, tenant), so nothing
                    /// secret ever crosses this boundary.
                    fn invoke(
                        capability_id: _rt::String,
                        input: _rt::Vec<u8>,
                    ) -> Result<_rt::Vec<u8>, ErrorInfo>;
                }
                #[doc(hidden)]
                macro_rules! __export_runtara_agent_mailgun_capabilities_0_3_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "runtara:agent-mailgun/capabilities@0.3.0#invoke")] unsafe extern
                        "C" fn export_invoke(arg0 : * mut u8, arg1 : usize, arg2 : * mut
                        u8, arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_invoke_cabi::<$ty > (arg0, arg1, arg2, arg3) } } #[unsafe
                        (export_name =
                        "cabi_post_runtara:agent-mailgun/capabilities@0.3.0#invoke")]
                        unsafe extern "C" fn _post_return_invoke(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_invoke::<$ty > (arg0)
                        } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_runtara_agent_mailgun_capabilities_0_3_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 40 + 10 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 40
                        + 10 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_agent_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::runtara::agent_mailgun::capabilities::__export_runtara_agent_mailgun_capabilities_0_3_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::runtara::agent_mailgun::capabilities);
    };
}
#[doc(inline)]
pub(crate) use __export_agent_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:runtara:agent-mailgun@0.3.0:agent:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 431] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb3\x02\x01A\x02\x01\
A\x05\x01B\x04\x01kw\x01ks\x01r\x07\x04codes\x07messages\x08categorys\x08severit\
ys\x09retryable\x7f\x0eretry-after-ms\0\x0aattributes\x01\x04\0\x0aerror-info\x03\
\0\x02\x03\0\x19runtara:agent/types@0.3.0\x05\0\x02\x03\0\0\x0aerror-info\x01B\x06\
\x02\x03\x02\x01\x01\x04\0\x0aerror-info\x03\0\0\x01p}\x01j\x01\x02\x01\x01\x01@\
\x02\x0dcapability-ids\x05input\x02\0\x03\x04\0\x06invoke\x01\x04\x04\0(runtara:\
agent-mailgun/capabilities@0.3.0\x05\x02\x04\0!runtara:agent-mailgun/agent@0.3.0\
\x04\0\x0b\x0b\x01\0\x05agent\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
