(component
  (import "wasi:http/types@0.2.3" (instance $types
    (type $dns (record (field "rcode" (option string)) (field "info-code" (option u16))))
    (export "DNS-error-payload" (type $dns-e (eq $dns)))
    (type $tls (record (field "alert-id" (option u8)) (field "alert-message" (option string))))
    (export "TLS-alert-received-payload" (type $tls-e (eq $tls)))
    (type $field-size (record (field "field-name" (option string)) (field "field-size" (option u32))))
    (export "field-size-payload" (type $field-size-e (eq $field-size)))
    (type $error-code (variant
      (case "DNS-timeout") (case "DNS-error" $dns-e) (case "destination-not-found")
      (case "destination-unavailable") (case "destination-IP-prohibited")
      (case "destination-IP-unroutable") (case "connection-refused")
      (case "connection-terminated") (case "connection-timeout")
      (case "connection-read-timeout") (case "connection-write-timeout")
      (case "connection-limit-reached") (case "TLS-protocol-error")
      (case "TLS-certificate-error") (case "TLS-alert-received" $tls-e)
      (case "HTTP-request-denied") (case "HTTP-request-length-required")
      (case "HTTP-request-body-size" (option u64)) (case "HTTP-request-method-invalid")
      (case "HTTP-request-URI-invalid") (case "HTTP-request-URI-too-long")
      (case "HTTP-request-header-section-size" (option u32))
      (case "HTTP-request-header-size" (option $field-size-e))
      (case "HTTP-request-trailer-section-size" (option u32))
      (case "HTTP-request-trailer-size" $field-size-e) (case "HTTP-response-incomplete")
      (case "HTTP-response-header-section-size" (option u32))
      (case "HTTP-response-header-size" $field-size-e)
      (case "HTTP-response-body-size" (option u64))
      (case "HTTP-response-trailer-section-size" (option u32))
      (case "HTTP-response-trailer-size" $field-size-e)
      (case "HTTP-response-transfer-coding" (option string))
      (case "HTTP-response-content-coding" (option string)) (case "HTTP-response-timeout")
      (case "HTTP-upgrade-failed") (case "HTTP-protocol-error") (case "loop-detected")
      (case "configuration-error") (case "internal-error" (option string))))
    (export "error-code" (type $error-code-e (eq $error-code)))
    (export "fields" (type $fields (sub resource)))
    (export "outgoing-request" (type $request (sub resource)))
    (export "request-options" (type $options (sub resource)))
    (export "future-incoming-response" (type $future (sub resource)))
    (type $scheme (variant (case "HTTP") (case "HTTPS") (case "other" string)))
    (export "scheme" (type $scheme-e (eq $scheme)))
    (type $own-fields (own $fields))
    (type $own-request (own $request))
    (type $borrow-request (borrow $request))
    (type $unit (result))
    (export "[constructor]fields" (func (result $own-fields)))
    (export "[constructor]outgoing-request" (func (param "headers" $own-fields) (result $own-request)))
    (export "[method]outgoing-request.set-scheme"
      (func (param "self" $borrow-request) (param "scheme" (option $scheme-e)) (result $unit)))
    (export "[method]outgoing-request.set-authority"
      (func (param "self" $borrow-request) (param "authority" (option string)) (result $unit)))
    (export "[method]outgoing-request.set-path-with-query"
      (func (param "self" $borrow-request) (param "path-with-query" (option string)) (result $unit)))))
  (alias export $types "outgoing-request" (type $request))
  (alias export $types "request-options" (type $options))
  (alias export $types "future-incoming-response" (type $future))
  (alias export $types "error-code" (type $error-code))
  (import "wasi:http/outgoing-handler@0.2.3" (instance $handler
    (export "outgoing-request" (type $request-e (eq $request)))
    (export "request-options" (type $options-e (eq $options)))
    (export "future-incoming-response" (type $future-e (eq $future)))
    (export "error-code" (type $error-code-e (eq $error-code)))
    (type $own-request (own $request-e))
    (type $own-options (own $options-e))
    (type $own-future (own $future-e))
    (export "handle" (func (param "request" $own-request) (param "options" (option $own-options))
      (result (result $own-future (error $error-code-e)))))))
  (core module $memory
    (memory (export "memory") 1)
    (global $heap (mut i32) (i32.const 4096))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $ptr i32)
      global.get $heap i32.const 7 i32.add i32.const -8 i32.and local.tee $ptr
      local.get 3 i32.add global.set $heap local.get $ptr))
  (core instance $mem (instantiate $memory))
  (alias export $types "[constructor]fields" (func $new-fields))
  (alias export $types "[constructor]outgoing-request" (func $new-request))
  (alias export $types "[method]outgoing-request.set-scheme" (func $set-scheme))
  (alias export $types "[method]outgoing-request.set-authority" (func $set-authority))
  (alias export $types "[method]outgoing-request.set-path-with-query" (func $set-path))
  (alias export $handler "handle" (func $handle))
  (core func $new-fields (canon lower (func $new-fields)))
  (core func $new-request (canon lower (func $new-request)))
  (core func $set-scheme (canon lower (func $set-scheme) (memory $mem "memory")))
  (core func $set-authority (canon lower (func $set-authority) (memory $mem "memory")))
  (core func $set-path (canon lower (func $set-path) (memory $mem "memory")))
  (core func $handle (canon lower (func $handle) (memory $mem "memory") (realloc (func $mem "realloc"))))
  (core module $code
    (import "mem" "memory" (memory 1))
    (import "host" "new-fields" (func $new-fields (result i32)))
    (import "host" "new-request" (func $new-request (param i32) (result i32)))
    (import "host" "set-scheme" (func $set-scheme (param i32 i32 i32 i32 i32) (result i32)))
    (import "host" "set-authority" (func $set-authority (param i32 i32 i32 i32) (result i32)))
    (import "host" "set-path" (func $set-path (param i32 i32 i32 i32) (result i32)))
    (import "host" "handle" (func $handle (param i32 i32 i32 i32)))
    (data (i32.const 0) "/")
    (data (i32.const 16) "{{AUTHORITY}}")
    ;; Build `GET http://{{AUTHORITY}}/` and hand it to the raw outgoing
    ;; handler. The completed output is two bytes: the result discriminant
    ;; (1 = error) and the error-code case (15 = HTTP-request-denied).
    (func (export "invoke") (param i32 i32 i32 i32) (result i32)
      (local $request i32)
      (call $new-request (call $new-fields)) local.set $request
      (call $set-scheme (local.get $request) (i32.const 1) (i32.const 0) (i32.const 0) (i32.const 0))
      if unreachable end
      (call $set-authority (local.get $request) (i32.const 1) (i32.const 16) (i32.const {{AUTHORITY_LEN}}))
      if unreachable end
      (call $set-path (local.get $request) (i32.const 1) (i32.const 0) (i32.const 1))
      if unreachable end
      (call $handle (local.get $request) (i32.const 0) (i32.const 0) (i32.const 256))
      (i32.store8 (i32.const 3000) (i32.load8_u (i32.const 256)))
      (i32.store8 (i32.const 3001) (i32.load8_u (i32.const 264)))
      (i32.store (i32.const 2048) (i32.const 0))
      (i32.store (i32.const 2056) (i32.const 0))
      (i32.store (i32.const 2060) (i32.const 3000))
      (i32.store (i32.const 2064) (i32.const 2))
      i32.const 2048))
  (core instance $code (instantiate $code (with "mem" (instance $mem))
    (with "host" (instance
      (export "new-fields" (func $new-fields)) (export "new-request" (func $new-request))
      (export "set-scheme" (func $set-scheme)) (export "set-authority" (func $set-authority))
      (export "set-path" (func $set-path)) (export "handle" (func $handle))))))
  (type $error (record (field "code" string) (field "message" string) (field "category" string)
    (field "severity" string) (field "retryable" bool) (field "retry-after-ms" (option u64)) (field "attributes" (option string))))
  (type $signal (record (field "checkpoint-id" string) (field "deadline-ms" (option u64))))
  (type $wake (variant (case "at" u64) (case "on-signal" $signal) (case "on-resume") (case "instances" string)))
  (type $suspension (record (field "wakes" (list $wake)) (field "state" (list u8))))
  (type $outcome (variant (case "completed" (list u8)) (case "suspended" $suspension)))
  (func $invoke async (param "capability-id" string) (param "input" (list u8)) (result (result $outcome (error $error)))
    (canon lift (core func $code "invoke") (memory $mem "memory") (realloc (func $mem "realloc"))))
  (instance $lifecycle
    (export "error-info" (type $error)) (export "signal-wait" (type $signal)) (export "wake" (type $wake))
    (export "suspension" (type $suspension)) (export "outcome" (type $outcome)) (export "invoke" (func $invoke)))
  (export "runtara:agent-workflow-agent/capabilities@1.0.0" (instance $lifecycle)))
