//! Optional atomic persistence for isolated invocation ownership.
//!
//! This contract stores control state, never invocation results. Callers keep
//! compiler checkpoint keys unchanged and authorize those keys before entry.
//! It is not used by ordinary non-durable calls: those arbitrate in memory until
//! a durable control command requires a tombstone. A backend must provide every
//! operation atomically; checking a token and later issuing an unfenced write
//! does not implement this contract.
use async_trait::async_trait;

/// Current host owner of an isolated root execution.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InvocationLease {
    /// Tenant resolved by trusted execution admission.
    pub tenant_id: String,
    /// Public root instance identity.
    pub instance_id: String,
    /// Opaque launch identity, generated by the host.
    pub owner: String,
    /// Monotonic root lease generation, allocated by the store.
    pub epoch: i64,
}

/// Durable owner facts for crash recovery before an exact revocation/CAS claim.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InvocationLeaseState {
    /// Current owner and its epoch.
    pub lease: InvocationLease,
    /// False after revocation; revocation does not establish that teardown ended.
    pub active: bool,
}

/// Exact execution attempt; neither a bare step ID nor guest-selected authority.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AttemptFence {
    /// Lease under which the attempt was admitted.
    pub lease: InvocationLease,
    /// Compiler-qualified logical address, stable across root replay.
    pub path: String,
    /// Store-allocated generation, independent of the guest's retry counter.
    pub generation: i64,
    /// Host start-request identity, retained for idempotent admission.
    pub start_id: String,
}

/// Arbitration state. Settled does not mean success and contains no result cache.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AttemptState {
    /// Writes and settlement may still win.
    Active,
    /// An invocation outcome was committed; late cancellation is a no-op.
    Settled,
    /// Cancellation won; replay must observe this tombstone before starting IO.
    Cancelled,
}

/// Stored attempt and its arbitration state.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InvocationAttempt {
    /// Exact authority to pass to subsequent operations.
    pub fence: AttemptFence,
    /// Current state, including a cancellation retained across replay.
    pub state: AttemptState,
}

/// Existing logical checkpoint bytes, optionally committed with settlement.
#[derive(Clone, Debug)]
pub struct InvocationCheckpoint {
    /// Already-authorized compiler checkpoint key; never prefixed here.
    pub checkpoint_id: String,
    /// Empty bytes are a read probe, matching the runtime checkpoint contract.
    pub state: Vec<u8>,
}

/// Result of a fenced checkpoint read-or-insert.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InvocationCheckpointResult {
    /// A checkpoint existed before this call; its first committed bytes win.
    pub found: bool,
    /// Existing bytes on a hit, empty on insertion or a missing read probe.
    pub state: Vec<u8>,
}

/// Settlement result, including existing checkpoint bytes when another commit
/// already established the logical replay value. Callers must honor that value.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InvocationSettlement {
    /// Winner of cancellation/completion arbitration.
    pub state: AttemptState,
    /// Read-or-insert result, only when this call won and requested a checkpoint.
    pub checkpoint: Option<InvocationCheckpointResult>,
}

/// A rejected mutation never changes lease, attempt or checkpoint state.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FenceRejection {
    /// Invalid or unrepresentable identity/counter.
    InvalidIdentity,
    /// No root owned by this tenant; do not disclose another tenant's state.
    UnknownRoot,
    /// The root is not running.
    InactiveRoot,
    /// Missing, revoked or superseded lease.
    LeaseMismatch,
    /// Another active start owns this path in the same lease.
    Busy,
    /// Unknown, forged or superseded attempt.
    AttemptMismatch,
    /// Cancellation already won.
    Cancelled,
    /// An outcome already won.
    Settled,
}

/// Storage failures are distinct from an expected arbitration rejection.
#[derive(Debug, thiserror::Error)]
pub enum InvocationFenceError {
    /// The requested transition did not own the current state.
    #[error("invocation fence rejected: {0:?}")]
    Rejected(FenceRejection),
    /// Backend failure; callers must not treat this as permission to proceed.
    #[error("invocation fence storage failed: {0}")]
    Storage(String),
}

/// Result of an atomic invocation operation.
pub type FenceResult<T> = Result<T, InvocationFenceError>;

/// Validate bounded, nonempty opaque identities without interpreting graph syntax.
pub fn validate_identity(value: &str) -> FenceResult<()> {
    if value.is_empty() || value.len() > 4096 || value.contains('\0') {
        return Err(InvocationFenceError::Rejected(
            FenceRejection::InvalidIdentity,
        ));
    }
    Ok(())
}

/// Optional capability exposed by [`super::Persistence::invocation_fences`].
/// All methods serialize with root terminal transitions and each other. A root
/// lease must be revoked before another owner can claim it. Revocation fences
/// writes; it does not kill Stores or reclaim their resources. The runner must
/// still join the old execution before releasing its capacity.
#[async_trait]
pub trait InvocationFences: Send + Sync {
    /// Inspect the current owner for a tenant-owned root, including parked or
    /// terminal roots. A root with no lease returns None. This snapshot grants
    /// no mutation authority by itself; subsequent transitions still use CAS.
    async fn get_invocation_lease(
        &self,
        tenant: &str,
        instance: &str,
    ) -> FenceResult<Option<InvocationLeaseState>>;

    /// Claim first ownership with `None`, or replace exactly the revoked epoch.
    /// A retry with the same owner and expected epoch returns the same lease.
    /// Running owners cannot be silently displaced, and epochs never repeat.
    async fn claim_invocation_lease(
        &self,
        tenant: &str,
        instance: &str,
        owner: &str,
        expected_epoch: Option<i64>,
    ) -> FenceResult<InvocationLease>;
    /// Revoke exactly this owner, idempotently. Works after root termination.
    async fn revoke_invocation_lease(&self, lease: &InvocationLease) -> FenceResult<()>;
    /// Admit a queued durable invocation before constructing a Store. Retrying
    /// the same start ID in this lease returns its original attempt. A different
    /// start may follow settlement, or reclaim an abandoned older lease, using
    /// a new generation. A cancelled logical path returns its tombstone instead
    /// of admitting another generation, including after a root relaunch.
    async fn begin_invocation_attempt(
        &self,
        lease: &InvocationLease,
        path: &str,
        start_id: &str,
    ) -> FenceResult<InvocationAttempt>;
    /// Record exact-attempt cancellation, including while its root is parked.
    /// Completion wins over late cancel. An old generation cannot affect a new
    /// one. Command ID deduplication belongs to the execution-control layer.
    async fn cancel_invocation_attempt(&self, fence: &AttemptFence) -> FenceResult<AttemptState>;
    /// Commit an invocation outcome and optional existing logical checkpoint in
    /// one transaction. Cancellation returns Cancelled without writing bytes.
    /// Repeated settlement is a no-op; this ledger never stores result bytes.
    async fn settle_invocation_attempt(
        &self,
        fence: &AttemptFence,
        checkpoint: Option<&InvocationCheckpoint>,
    ) -> FenceResult<InvocationSettlement>;
    /// Read/insert a checkpoint and update the root's checkpoint pointer under
    /// the same lease/attempt fence. Existing state is never overwritten. Empty
    /// state is a probe and does not create an empty replay hit.
    async fn invocation_checkpoint(
        &self,
        fence: &AttemptFence,
        checkpoint: &InvocationCheckpoint,
    ) -> FenceResult<InvocationCheckpointResult>;
}
