#!/usr/bin/env bash
# Runtara Bootstrap Installer
#
# Hosted at install.runtara.com — downloads the real install.sh from the
# matching GitHub release and executes it.
#
# Usage:
#   curl -fsSL https://install.runtara.com | sh
#   curl -fsSL https://install.runtara.com | sh -s -- --version 1.6.10
#   curl -fsSL https://install.runtara.com | sh -s -- --user
#   curl -fsSL https://install.runtara.com | sh -s -- --docker
#   curl -fsSL https://install.runtara.com | sh -s -- --docker-persist

set -eu

GITHUB_REPO="runtarahq/runtara"

# ─── Colour helpers ─────────────────────────────────────────────────────────

if [ -t 1 ]; then
    GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
    BOLD='\033[1m'; NC='\033[0m'
else
    GREEN='' YELLOW='' RED='' BOLD='' NC=''
fi

info() { printf "${GREEN}[+]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[!]${NC} %s\n" "$*"; }
err()  { printf "${RED}[x]${NC} %s\n" "$*" >&2; }
step() { printf "\n${BOLD}%s${NC}\n" "==> $*"; }

# ─── Parse args ────────────────────────────────────────────────────────────

VERSION=""
DO_DOCKER=0
DOCKER_PERSIST=0
DOCKER_DIR=""
PASSTHROUGH_ARGS=()

while [ $# -gt 0 ]; do
    case "$1" in
        --version)        VERSION="$2"; PASSTHROUGH_ARGS+=("$1" "$2"); shift 2 ;;
        --version=*)      VERSION="${1#*=}"; PASSTHROUGH_ARGS+=("$1"); shift ;;
        --docker)         DO_DOCKER=1; shift ;;
        --docker-persist) DO_DOCKER=1; DOCKER_PERSIST=1; shift ;;
        --docker-dir)     DOCKER_DIR="$2"; shift 2 ;;
        --docker-dir=*)   DOCKER_DIR="${1#*=}"; shift ;;
        *)                PASSTHROUGH_ARGS+=("$1"); shift ;;
    esac
done

# ─── Resolve version ───────────────────────────────────────────────────────

# Map version to git tag: "dev" -> "dev", anything else -> "v1.2.3"
version_to_tag() {
    if [ "$1" = "dev" ]; then echo "dev"; else echo "v$1"; fi
}

if [ -z "$VERSION" ]; then
    info "Resolving latest Runtara version..."
    VERSION="$(curl -fsSL "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" \
        | sed -n 's/.*"tag_name":[[:space:]]*"v\([^"]*\)".*/\1/p')"
    if [ -z "$VERSION" ]; then
        err "Failed to resolve latest version from GitHub."
        exit 1
    fi
    # Inject resolved version so install.sh doesn't re-resolve
    PASSTHROUGH_ARGS+=("--version" "$VERSION")
fi

TAG="$(version_to_tag "$VERSION")"
info "Runtara v${VERSION} (tag: ${TAG})"

# ─── Docker simple mode ───────────────────────────────────────────────────

if [ "$DO_DOCKER" = "1" ]; then
    # Check for docker
    if ! command -v docker > /dev/null 2>&1; then
        err "docker not found. Install Docker first: https://docs.docker.com/get-docker/"
        exit 1
    fi
    if ! docker compose version > /dev/null 2>&1; then
        err "docker compose plugin not found. Install Docker Compose: https://docs.docker.com/compose/install/"
        exit 1
    fi

    dir="${DOCKER_DIR:-${HOME}/.runtara-docker}"
    mkdir -p "$dir"
    info "Docker directory: ${dir}"

    server_port="${SERVER_PORT:-7001}"
    pg_port="${POSTGRES_PORT:-5432}"
    vk_port="${VALKEY_PORT:-6379}"
    tenant_id="${TENANT_ID:-default}"

    pg_volume="runtara-pgdata:/var/lib/postgresql/data"
    vk_volume="runtara-valkey:/data"
    volume_block=""
    if [ "$DOCKER_PERSIST" = "1" ]; then
        info "Persistent volumes enabled"
        volume_block="
volumes:
    runtara-pgdata:
    runtara-valkey:"
    else
        info "Ephemeral mode (data lost on 'docker compose down')"
        pg_volume=""
        vk_volume=""
    fi

    # init SQL
    cat > "${dir}/init-db.sql" <<'SQLEOF'
CREATE DATABASE runtara_objects OWNER runtara;
SQLEOF

    # Dockerfile — uses the released install.sh to install the bundle
    cat > "${dir}/Dockerfile" <<DKEOF
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y curl ca-certificates && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://github.com/${GITHUB_REPO}/releases/download/${TAG}/install.sh | \\
    bash -s -- --user --skip-service --version ${VERSION}

ENV PATH="/root/.runtara/toolchain/bin:/root/.runtara/bin:\${PATH}"
ENV LD_LIBRARY_PATH="/root/.runtara/toolchain/lib"
ENV RUNTARA_WASM_LIBRARY_DIR="/root/.runtara/stdlib"
ENV WASMTIME_PATH="/root/.runtara/bin/wasmtime"

EXPOSE 7001

CMD ["runtara-server"]
DKEOF

    # docker-compose.yml
    cat > "${dir}/docker-compose.yml" <<COMPOSEEOF
# Runtara simple mode — generated by install.runtara.com --docker
# Manage with: docker compose -f ${dir}/docker-compose.yml [up -d|down|logs]

services:
    postgres:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_USER: runtara
            POSTGRES_PASSWORD: runtara
            POSTGRES_DB: runtara
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U runtara"]
            interval: 2s
            timeout: 5s
            retries: 10
        ports:
            - "${pg_port}:5432"
        volumes:
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
$([ -n "$pg_volume" ] && printf '            - %s\n' "$pg_volume" || true)

    valkey:
        image: valkey/valkey:7.2
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "valkey-cli", "ping"]
            interval: 2s
            timeout: 5s
            retries: 10
        ports:
            - "${vk_port}:6379"
$([ -n "$vk_volume" ] && printf '        volumes:\n            - %s\n' "$vk_volume")

    runtara:
        build: .
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
            valkey:
                condition: service_healthy
        environment:
            RUNTARA_DATABASE_URL: postgres://runtara:runtara@postgres/runtara
            OBJECT_MODEL_DATABASE_URL: postgres://runtara:runtara@postgres/runtara_objects
            DATA_DIR: /tmp/runtara-data
            VALKEY_HOST: valkey
            VALKEY_PORT: "6379"
            TENANT_ID: "${tenant_id}"
            SERVER_PORT: "7001"
            RUST_LOG: "runtara_server=info,runtara_core=info,runtara_environment=info"
        ports:
            - "${server_port}:7001"
${volume_block}
COMPOSEEOF

    info "Wrote ${dir}/docker-compose.yml"

    step "Starting Runtara stack"
    docker compose -f "${dir}/docker-compose.yml" up -d --wait || {
        err "Failed to start. Check logs with:"
        err "  docker compose -f ${dir}/docker-compose.yml logs"
        exit 1
    }

    echo ""
    printf '%s  Runtara v%s is running!%s\n' "${GREEN}${BOLD}" "$VERSION" "$NC"
    echo ""
    echo "  API:        http://localhost:${server_port}"
    echo "  Postgres:   localhost:${pg_port} (runtara/runtara)"
    echo "  Valkey:     localhost:${vk_port}"
    echo "  Compose:    ${dir}/docker-compose.yml"
    echo ""
    echo "  Commands:"
    echo "    docker compose -f ${dir}/docker-compose.yml logs -f    # follow logs"
    echo "    docker compose -f ${dir}/docker-compose.yml down       # stop"
    if [ "$DOCKER_PERSIST" = "1" ]; then
        echo "    docker compose -f ${dir}/docker-compose.yml down -v   # stop & delete data"
    fi
    echo "    docker compose -f ${dir}/docker-compose.yml up -d     # start again"
    echo ""
    exit 0
fi

# ─── Download and execute the real installer ────────────────────────────────

INSTALL_URL="https://github.com/${GITHUB_REPO}/releases/download/${TAG}/install.sh"

info "Fetching installer from release ${TAG}..."

INSTALLER="$(curl -fsSL "$INSTALL_URL")" || {
    err "Failed to download install.sh from ${INSTALL_URL}"
    err "Check that release ${TAG} exists: https://github.com/${GITHUB_REPO}/releases/tag/${TAG}"
    exit 1
}

exec sh -c "$INSTALLER" -- "${PASSTHROUGH_ARGS[@]}"
