import {
  AlertTriangle,
  Asterisk,
  BadgeCheck,
  Bot,
  Braces,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  CircleHelp,
  Code,
  Cog,
  Columns,
  Copy,
  DollarSign,
  Eye,
  FileClock,
  GitBranch,
  Group,
  Hash,
  Hourglass,
  Inbox,
  Info,
  List,
  ListFilter,
  Loader2,
  LogInIcon,
  LogOut,
  Mail,
  Maximize2,
  Merge,
  MoreHorizontal,
  PlayCircle,
  Plus,
  Radio,
  Rocket,
  Search,
  Sparkles,
  Split,
  SquarePen,
  SquarePlus,
  Star,
  StopCircle,
  ToggleLeft,
  Trash2,
  SquareMenu,
  History,
  User,
  Variable,
  X,
  Type,
  SquareCheck,
  Key,
} from 'lucide-react';
import SlackLogo from '@/assets/logo/slack_logo.svg';

export const Icons: Record<string, any> = {
  spinner: Loader2,
  signIn: LogInIcon,
  signOut: LogOut,
  MoreHorizontal: MoreHorizontal,
  edit: SquarePen,
  remove: Trash2,
  slack: SlackLogo,
  chevronsUpDown: ChevronsUpDown,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  filter: ListFilter,
  help: CircleHelp,
  stop: StopCircle,
  gear: Cog,
  agent: Bot,
  split: Split,
  asterisk: Asterisk,
  merge: Merge,
  rocket: Rocket,
  add: Plus,
  start: PlayCircle,
  create: SquarePlus,
  history: FileClock,
  info: Info,
  wait: Hourglass,
  event: Radio,
  groupby: Group,
  entryPoint: Star,
  finish: BadgeCheck,
  copy: Copy,
  warning: AlertTriangle,
  sparkles: Sparkles,
  inbox: Inbox,
  squareMenu: SquareMenu,
  instances: History,
  // Additional icons for input mapping
  braces: Braces,
  calendar: Calendar,
  dollarSign: DollarSign,
  gitBranch: GitBranch,
  hash: Hash,
  list: List,
  mail: Mail,
  search: Search,
  toggleLeft: ToggleLeft,
  user: User,
  variable: Variable,
  x: X,
  type: Type,
  squareCheck: SquareCheck,
  key: Key,
  // Template editor icons
  maximize: Maximize2,
  eye: Eye,
  code: Code,
  columns: Columns,
  check: Check,
};
