//! AES-256-GCM cipher with a 256-bit key held in memory.
//!
//! The key is supplied at startup (typically via
//! [`crate::crypto::factory::cipher_from_env`]) and kept as a
//! [`zeroize::Zeroizing`] buffer so it's erased when dropped.
//!
//! Each [`encrypt`](CredentialCipher::encrypt) call uses a fresh 96-bit
//! random nonce generated by `OsRng`. AES-256-GCM tolerates ~2^32 nonces
//! per key before birthday bounds matter, well beyond any realistic
//! per-tenant throughput.

use aes_gcm::aead::{Aead, OsRng};
use aes_gcm::{AeadCore, Aes256Gcm, Key, KeyInit, Nonce};
use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use serde_json::{Value, json};
use zeroize::Zeroizing;

use super::cipher::{CipherError, CredentialCipher, ENVELOPE_ALG, ENVELOPE_VERSION, is_envelope};

/// AES-256-GCM cipher. See module docs.
pub struct AesGcmCipher {
    cipher: Aes256Gcm,
    key_id: String,
}

impl AesGcmCipher {
    /// Build a cipher from a 32-byte key.
    pub fn new(
        key_bytes: Zeroizing<Vec<u8>>,
        key_id: impl Into<String>,
    ) -> Result<Self, CipherError> {
        if key_bytes.len() != 32 {
            return Err(CipherError::InvalidKey(format!(
                "expected 32 bytes, got {}",
                key_bytes.len()
            )));
        }
        let key = Key::<Aes256Gcm>::from_slice(&key_bytes);
        let cipher = Aes256Gcm::new(key);
        Ok(Self {
            cipher,
            key_id: key_id.into(),
        })
    }

    /// Build a cipher from a base64-encoded 32-byte key.
    ///
    /// Accepts both standard and URL-safe base64, with or without padding.
    pub fn from_base64_key(key_b64: &str, key_id: impl Into<String>) -> Result<Self, CipherError> {
        let trimmed = key_b64.trim();
        // Try standard base64 first, then URL-safe as a fallback.
        let bytes = BASE64
            .decode(trimmed)
            .or_else(|_| base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(trimmed))
            .or_else(|_| base64::engine::general_purpose::URL_SAFE.decode(trimmed))
            .map_err(|e| CipherError::InvalidKey(format!("base64 decode failed: {}", e)))?;
        Self::new(Zeroizing::new(bytes), key_id)
    }
}

impl CredentialCipher for AesGcmCipher {
    fn encrypt(&self, plaintext: &Value) -> Result<Value, CipherError> {
        let plaintext_bytes = serde_json::to_vec(plaintext)
            .map_err(|e| CipherError::Encrypt(format!("json serialize: {}", e)))?;

        let nonce = Aes256Gcm::generate_nonce(&mut OsRng);
        let ciphertext = self
            .cipher
            .encrypt(&nonce, plaintext_bytes.as_slice())
            .map_err(|e| CipherError::Encrypt(format!("aead: {}", e)))?;

        Ok(json!({
            "v": ENVELOPE_VERSION,
            "alg": ENVELOPE_ALG,
            "kid": self.key_id,
            "nonce": BASE64.encode(nonce.as_slice()),
            "ct": BASE64.encode(&ciphertext),
        }))
    }

    fn decrypt(&self, stored: &Value) -> Result<Value, CipherError> {
        // Rollout passthrough: plaintext values flow through unchanged.
        if !is_envelope(stored) {
            return Ok(stored.clone());
        }

        let obj = stored
            .as_object()
            .ok_or_else(|| CipherError::InvalidEnvelope("not a JSON object".into()))?;

        let alg = obj
            .get("alg")
            .and_then(Value::as_str)
            .ok_or_else(|| CipherError::InvalidEnvelope("missing alg".into()))?;
        if alg != ENVELOPE_ALG {
            return Err(CipherError::InvalidEnvelope(format!(
                "unsupported algorithm: {}",
                alg
            )));
        }

        let version = obj.get("v").and_then(Value::as_u64).unwrap_or(0);
        if version != u64::from(ENVELOPE_VERSION) {
            return Err(CipherError::InvalidEnvelope(format!(
                "unsupported envelope version: {}",
                version
            )));
        }

        let nonce_b64 = obj
            .get("nonce")
            .and_then(Value::as_str)
            .ok_or_else(|| CipherError::InvalidEnvelope("missing nonce".into()))?;
        let ct_b64 = obj
            .get("ct")
            .and_then(Value::as_str)
            .ok_or_else(|| CipherError::InvalidEnvelope("missing ct".into()))?;

        let nonce_bytes = BASE64
            .decode(nonce_b64)
            .map_err(|e| CipherError::InvalidEnvelope(format!("nonce decode: {}", e)))?;
        if nonce_bytes.len() != 12 {
            return Err(CipherError::InvalidEnvelope(format!(
                "nonce must be 12 bytes, got {}",
                nonce_bytes.len()
            )));
        }
        let nonce = Nonce::from_slice(&nonce_bytes);

        let ct_bytes = BASE64
            .decode(ct_b64)
            .map_err(|e| CipherError::InvalidEnvelope(format!("ct decode: {}", e)))?;

        let plaintext_bytes = self
            .cipher
            .decrypt(nonce, ct_bytes.as_slice())
            .map_err(|_| CipherError::Decrypt("aead authentication failed".into()))?;

        serde_json::from_slice(&plaintext_bytes)
            .map_err(|e| CipherError::Decrypt(format!("json parse: {}", e)))
    }

    fn key_id(&self) -> &str {
        &self.key_id
    }

    fn is_encrypting(&self) -> bool {
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn test_key() -> Zeroizing<Vec<u8>> {
        Zeroizing::new(vec![0x42u8; 32])
    }

    #[test]
    fn rejects_wrong_key_length() {
        assert!(AesGcmCipher::new(Zeroizing::new(vec![0; 16]), "k").is_err());
        assert!(AesGcmCipher::new(Zeroizing::new(vec![0; 33]), "k").is_err());
    }

    #[test]
    fn roundtrip_preserves_json() {
        let cipher = AesGcmCipher::new(test_key(), "test-key").unwrap();
        let plaintext = json!({
            "api_key": "sk-abc123",
            "base_url": "https://api.example.com",
            "nested": {"foo": [1, 2, 3]}
        });
        let envelope = cipher.encrypt(&plaintext).unwrap();
        assert_ne!(envelope, plaintext);
        assert!(is_envelope(&envelope));
        let decrypted = cipher.decrypt(&envelope).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn envelope_has_expected_fields() {
        let cipher = AesGcmCipher::new(test_key(), "kid-123").unwrap();
        let envelope = cipher.encrypt(&json!({"secret": "value"})).unwrap();
        let obj = envelope.as_object().unwrap();
        assert_eq!(obj["v"], json!(1));
        assert_eq!(obj["alg"], json!("aes-256-gcm"));
        assert_eq!(obj["kid"], json!("kid-123"));
        assert!(!obj["nonce"].as_str().unwrap().is_empty());
        assert!(!obj["ct"].as_str().unwrap().is_empty());
    }

    #[test]
    fn nonces_are_unique() {
        let cipher = AesGcmCipher::new(test_key(), "k").unwrap();
        let plaintext = json!({"secret": "value"});
        let e1 = cipher.encrypt(&plaintext).unwrap();
        let e2 = cipher.encrypt(&plaintext).unwrap();
        // Same plaintext + same key, but different nonces => different ciphertexts.
        assert_ne!(e1["nonce"], e2["nonce"]);
        assert_ne!(e1["ct"], e2["ct"]);
        // Both decrypt to the same plaintext.
        assert_eq!(cipher.decrypt(&e1).unwrap(), plaintext);
        assert_eq!(cipher.decrypt(&e2).unwrap(), plaintext);
    }

    #[test]
    fn decrypt_rejects_tampered_ciphertext() {
        let cipher = AesGcmCipher::new(test_key(), "k").unwrap();
        let mut envelope = cipher.encrypt(&json!({"secret": "value"})).unwrap();
        // Flip a byte in the ciphertext.
        let ct = envelope["ct"].as_str().unwrap().to_string();
        let mut bytes = BASE64.decode(&ct).unwrap();
        bytes[0] ^= 0x01;
        envelope["ct"] = json!(BASE64.encode(&bytes));
        assert!(matches!(
            cipher.decrypt(&envelope),
            Err(CipherError::Decrypt(_))
        ));
    }

    #[test]
    fn decrypt_fails_with_wrong_key() {
        let a = AesGcmCipher::new(Zeroizing::new(vec![0x11; 32]), "a").unwrap();
        let b = AesGcmCipher::new(Zeroizing::new(vec![0x22; 32]), "b").unwrap();
        let envelope = a.encrypt(&json!({"secret": "value"})).unwrap();
        assert!(matches!(b.decrypt(&envelope), Err(CipherError::Decrypt(_))));
    }

    #[test]
    fn decrypt_passes_through_plaintext_for_rollout() {
        let cipher = AesGcmCipher::new(test_key(), "k").unwrap();
        let plaintext = json!({"api_key": "sk-123", "base_url": "https://x"});
        // Simulates reading a row that was written before encryption was enabled.
        assert_eq!(cipher.decrypt(&plaintext).unwrap(), plaintext);
    }

    #[test]
    fn decrypt_rejects_unknown_algorithm() {
        let cipher = AesGcmCipher::new(test_key(), "k").unwrap();
        let envelope = json!({
            "v": 1,
            "alg": "chacha20-poly1305",
            "kid": "x",
            "nonce": "AAAAAAAAAAAAAAAA",
            "ct": "AAAA"
        });
        assert!(matches!(
            cipher.decrypt(&envelope),
            Err(CipherError::InvalidEnvelope(_))
        ));
    }

    #[test]
    fn from_base64_key_accepts_standard_and_urlsafe() {
        // 32 zero bytes → base64 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
        let std_key = BASE64.encode(vec![0u8; 32]);
        assert!(AesGcmCipher::from_base64_key(&std_key, "k").is_ok());

        let url_key = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(vec![0u8; 32]);
        assert!(AesGcmCipher::from_base64_key(&url_key, "k").is_ok());
    }

    #[test]
    fn from_base64_key_rejects_wrong_length() {
        let short = BASE64.encode(vec![0u8; 16]);
        assert!(matches!(
            AesGcmCipher::from_base64_key(&short, "k"),
            Err(CipherError::InvalidKey(_))
        ));
    }

    #[test]
    fn is_encrypting_reports_true() {
        let cipher = AesGcmCipher::new(test_key(), "k").unwrap();
        assert!(cipher.is_encrypting());
    }
}
